examples/tool_calling_agent_ollama.py, src/smolagents/models.py
Hi @aymeric-roucher,
first of all: smolagents is super cool and easy to use!
This PR just adds support for remote LLM servers using LiteLLM. The only necessary change was to add `api_base` and `api_key` to some optional parameters to be able to call remote servers using the LiteLLMModel. 
I tested this with an institutional OpenAI-compatible server. I also add an Ollama-example allowing others to test it with a local server.
This also supersedes and closes #8 
Let me know what you think and Happy New Year!
Best,
Robert
=> Support remote llm servers

src/smolagents/models.py
thanks for the effort! 
A small fix on the example/docstring
=> Fix example usage in HfApiModel

src/smolagents/local_python_executor.py
=> chore: update local_python_executor.py

.gitignore, CODE_OF_CONDUCT.md, CONTRIBUTING.md
=> Add code of conduct and contributing guide

src/smolagents/models.py
adding support for more optiones to the liteLLM like temperature or seed for more controllable tests
=> Add support for additional keyword arguments in LiteLLMModel

README.md
=> Update README.md: add link to blog post

src/smolagents/default_tools.py, src/smolagents/gradio_ui.py
Replaces https://github.com/huggingface/smolagents/pull/107, fixes https://github.com/huggingface/smolagents/issues/86
=> Change DuckDuckGoSearchTool output_type to string

src/smolagents/agents.py, src/smolagents/models.py, src/smolagents/utils.py, tests/test_utils.py
Solves https://github.com/huggingface/smolagents/issues/114.
=> Support multiple code blobs

docs/source/en/reference/tools.md, docs/source/en/tutorials/tools.md, src/smolagents/agents.py, src/smolagents/default_tools.py, src/smolagents/models.py, src/smolagents/tools.py, tests/test_agents.py, tests/test_python_interpreter.py, tests/test_search.py
Prepare for OpenTelemetry support (conditional on merging this: https://github.com/Arize-ai/openinference/pull/1184).
Simplifies the tool system vastly by removing class `Toolbox`.
=> Support OpenTelemetry

src/smolagents/tools.py
=> Tools from Spaces: Fix bug preventing use of long prompts.

src/smolagents/utils.py
Fix typo in comment, thank you very much.
=> Fix typo in comment

src/smolagents/monitoring.py, src/smolagents/tools.py, src/smolagents/utils.py
Fix quality issues. see: https://github.com/huggingface/smolagents/actions/runs/12741986053/job/35509413878?pr=170
```
Would reformat: src/smolagents/monitoring.py
Would reformat: src/smolagents/tools.py
Would reformat: src/smolagents/utils.py
3 files would be reformatted, 21 files already formatted
```
I think these quality issues are raised after the latest 0.9 ruff version release on Jan 9: https://pypi.org/project/ruff/0.9.0/
=> Fix quality issues

src/smolagents/agents.py
=> Fix tool_calls parsing error in `ToolCallingAgent` when using `OpenAIServerModel`

docs/source/en/tutorials/building_good_agents.md
Fix minor issues in building_good_agents docs.
=> Fix minor issues in building_good_agents docs

src/smolagents/local_python_executor.py
=> Implemented support for ast.Pass in the interpeter.

src/smolagents/models.py, tests/test_models.py
This adds support for OpenTelemetry, following up on the support for smolagents in https://github.com/Arize-ai/openinference/issues/1195!
=> Add support for OpenTelemetry instrumentation 📊

examples/benchmark.ipynb
Rename the benchmark dataset split from train to test.
Note that the split was renamed in the corresponding dataset: https://huggingface.co/datasets/m-ric/smol_agents_benchmark
=> Rename the split of the benchmark dataset from train to test

docs/source/zh/guided_tour.md, docs/source/zh/tutorials/tools.md
Added the two previous bug fixes also to the zh docs.
=> Fix code examples with additional_args and num_ctx examples also in zh docs

src/smolagents/agents.py
=> Fix CI quality issue

src/smolagents/agents.py, src/smolagents/local_python_executor.py, src/smolagents/tools.py, tests/test_agents.py, tests/test_python_interpreter.py, tests/test_tools.py
I just separated this from https://github.com/huggingface/smolagents/pull/220 since this logic stands by itself.
=> Improve python executor's error logging

tests/test_python_interpreter.py
Fix CI quality issue introduced in:
- #274
=> Fix CI quality

docs/source/en/tutorials/secure_code_execution.md, pyproject.toml, src/smolagents/e2b_executor.py
=> Make e2b optional dependency

src/smolagents/agents.py
Fix arg passing to AgentExecutionError.
This was introduced in:
- #303
=> Fix arg passing to AgentExecutionError

docs/source/en/reference/agents.md, src/smolagents/agents.py
Add args to `MultiStepAgent` docstring.
=> Add args to MultiStepAgent docstring

README.md
Update README instructions to run tests: `make test`
=> Update README instructions to run tests

docs/source/en/reference/agents.md, src/smolagents/agents.py
Fix syntax of `MultiStepAgent` docstring.
=> Fix MultiStepAgent docstring

src/smolagents/models.py
=> Fix docstrings of models

src/smolagents/gradio_ui.py
Add the option to pass more args to gradio launch
closes https://github.com/huggingface/smolagents/issues/365
=> add kwargs to gradio launch

docs/source/zh/examples/text_to_sql.md
This PR adds Chinese translation for the text-to-sql example. Once this PR is merged, https://github.com/huggingface/smolagents/issues/141 should be closed.
=> Add Chinese translations for text-to-sql example

docs/source/zh/examples/rag.md
This PR relates to https://github.com/huggingface/smolagents/issues/141.
Please freel free to make any comments. Thanks. 
=> Add Chinese translations for RAG

examples/vlm_web_browser.py
=> `Qwen-2VL` -> `Qwen2-VL` model name typo fixed

.github/workflows/tests.yml, tests/test_import.py
Test import without extras.
See:
- #360
=> Test import without extras

pyproject.toml, src/smolagents/__init__.py
Bump dev version: v1.7.0.dev0.
=> Bump dev version: v1.7.0.dev0

src/smolagents/agents.py
Doing some stuff downstream of `smolagents` and noticed this small issue
=> Fix return type of generator function in `Agent._run()`

docs/source/en/guided_tour.md, docs/source/en/index.md, docs/source/en/reference/models.md, pyproject.toml, src/smolagents/__init__.py, src/smolagents/models.py, tests/test_agents.py, tests/test_all_docs.py, tests/test_models.py
=> Support third-party Inference providers in `HfApiModel`

src/smolagents/memory.py
Fix import from deleted logger module.
Note that the logger module was deleted in:
- #419
=> Fix import from deleted logger module

src/smolagents/agents.py, tests/test_agents.py
Fix MultiStepAgent.planning_step message content.
=> Fix MultiStepAgent.planning_step message content

src/smolagents/e2b_executor.py
Minor issue left to resolve in PR #319 
Closes #434
=> Fix minor issue in e2b

src/smolagents/default_tools.py, tests/test_default_tools.py
Fix `SpeechToTextTool` new instance.
Fix #473.
=> Fix SpeechToTextTool new instance

docs/source/en/examples/web_browser.md
Just as the title says 😄 
By the way, is there any model that already has a longer [context](https://github.com/huggingface/smolagents/pull/416#issue-2818406203) that may be used for this example with `HfApiModel`? @aymeric-roucher @merveenoyan
=> Added `HfApiModel` import to `web browser example`

pyproject.toml
=> Bump litellm to 1.60.2 (fixes #34)

src/smolagents/agents.py, tests/test_agents.py
Define `step_number` as attribute and initialize it.
Related to:
- #495
=> Initialize step_number attribute

pyproject.toml
Delete non-exisiting accelerate extra from all extra.
=> Delete non-exisiting accelerate extra

docs/source/en/guided_tour.md
=> Fix managed agent example

docs/source/en/guided_tour.md
=> Minor fix in the guilded_tour docs

src/smolagents/agents.py, tests/test_agents.py
Do not pass system prompt to update plan and test plan prompts.
=> Do not pass system prompt to update plan and test plan prompts

docs/source/en/guided_tour.md
Remove unused import in guided_tour docs.
=> Remove unused import in guided_tour docs

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Test evaluate_delete.
The evaluate_delete function was introduced in:
- #317
=> Test evaluate_delete

docs/source/en/reference/agents.md, docs/source/hi/reference/agents.md, docs/source/zh/reference/agents.md, src/smolagents/agents.py, src/smolagents/prompts/code_agent.yaml, src/smolagents/prompts/toolcalling_agent.yaml, tests/test_agents.py
Refactor and test final answer prompts.
=> Refactor and test final answer prompts

README.md
changed `--model` to `--model-type`
=> corrected typo in README.md

README.md
Before
```
webagent --prompt {prompt content}
```
After
```
webagent {prompt content}
```
=> Remove --prompt argument of instance instruction in README.md

src/smolagents/models.py
Fix style by removing trailing whitespace.
This style issue was introduced in:
- #300
=> Fix CI quality check by removing trailing whitespace

examples/open_deep_research/README.md
Fix installation instructions in Open-DeepResearch README.
Fix #611.
=> Fix installation instructions in Open-DeepResearch README

docs/source/zh/reference/agents.md, docs/source/zh/reference/models.md, docs/source/zh/reference/tools.md
Translate docs from English to Chinese
=> Contribute to the documentation

src/smolagents/agents.py
Fix PlanningPromptTemplate and its docstring.
Issue introduced by:
- #591
=> Fix PlanningPromptTemplate and its docstring

src/smolagents/agents.py
Add docstring args for `MultiStepAgent.from_folder`.
=> Add docstring args for MultiStepAgent.from_folder

src/smolagents/agents.py, src/smolagents/default_tools.py, tests/test_agents.py
Changed the default tool names to avoid errors due to same name tools, and a minor fix in `agents.py`.
=> Minor fix save agents

src/smolagents/agents.py
Fixed misspelling: "when" misspelled as "whene" on line 391 in agents.py
=> Fix typo in error message

.github/workflows/tests.yml, tests/test_tool_validation.py
Test `validate_tool_attributes`.
Related to:
- #579
=> Test validate_tool_attributes

README.md
=> Remove translation tool from README

docs/source/en/tutorials/inspect_runs.mdx
=> Fixed typo in Telemetry docs

src/smolagents/agents.py
=> Fix duplicate managed agent name and its tool name

docs/source/en/tutorials/building_good_agents.mdx, docs/source/hi/tutorials/building_good_agents.mdx, docs/source/zh/tutorials/building_good_agents.mdx
Update in docs how to change prompts.
Fix #718.
=> Update docs on how to change prompts

src/smolagents/cli.py
=> Add api-base and api-key arguments to CLI

examples/benchmark.ipynb
Add disclaimer in benchmark to request access for gated dataset.
Related to:
- #717
=> Add disclaimer in benchmark to request access for gated dataset

tests/test_all_docs.py, tests/test_models.py, tests/utils/markers.py
Define test RUN_ALL requirement marker in one file.
=> Define test RUN_ALL requirement marker in one file

pyproject.toml
Create docker extra installation dependency, in analogy with the e2b extra.
=> Create docker extra installation dependency

examples/open_deep_research/run.py, src/smolagents/agents.py, src/smolagents/local_python_executor.py, src/smolagents/monitoring.py, src/smolagents/utils.py, tests/test_agents.py, tests/test_local_python_executor.py
Fixes https://github.com/huggingface/smolagents/issues/751
=> Fix bracket logging in rich

src/smolagents/tools.py
Fix TypeError raised by launch_gradio_demo with PipelineTool:
> TypeError: TranslationTool.encode() got an unexpected keyword argument 'sanitize_inputs_outputs'
```python
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 625, in process_events
response = await route_utils.call_process_api(
File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
output = await app.get_blocks().process_api(
File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 2096, in process_api
result = await self.call_function(
File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1643, in call_function
prediction = await anyio.to_thread.run_sync(  # type: ignore
File …
```
=> Fix TypeError raised by launch_gradio_demo with PipelineTool

src/smolagents/agents.py, tests/test_agents.py
Support custom final_answer in agent init.
Related to:
- #769
Fix #759.
=> Support custom final_answer in agent init

docs/source/en/_toctree.yml
=> Secure code execution wrong title in docs TOC

examples/gradio_ui.py
Fix CI quality in examples/gradio_ui.
This issue was introduced in:
- #797
=> Fix CI quality in examples/gradio_ui

examples/open_deep_research/README.md
Improve setup instruction for Open DeepResearch.
Related to:
- #808
- #760
- #676
=> Improve setup instruction for Open DeepResearch

src/smolagents/default_tools.py
=> Minor fix of import in VisitWebpageTool

tests/test_memory.py
Fix CI test_action_step_to_messages.
The CI was broken with the merge of:
- #779
Fix #867.
=> Fix CI test_action_step_to_messages

pyproject.toml, src/smolagents/cli.py, src/smolagents/vision_web_browser.py, tests/test_cli.py
Add tests and refactor CLI.
New tests should catch errors like the one fixed by:
- #889
=> Add tests and refactor CLI

pyproject.toml
Bump mcpadapt >= 0.0.15.
Fix #626.
=> Bump mcpadapt >= 0.0.15

docs/source/en/tutorials/building_good_agents.mdx, docs/source/hi/tutorials/building_good_agents.mdx, docs/source/zh/tutorials/building_good_agents.mdx, src/smolagents/prompts/code_agent.yaml, src/smolagents/prompts/toolcalling_agent.yaml
Update docs about changing the system prompt.
- The system prompt is now different
- It no longer contains `{{tool_descriptions}}` or `{{managed_agents_description}}`
Also, remove unnecessary else Jinja statement from the prompt templates.
Fix #899.
=> Update docs about changing the system prompt

src/smolagents/utils.py
Improve docstring of `parse_code_blobs`.
=> Improve docstring of parse_code_blobs

pyproject.toml
Add `mlx-lm` to `all` extra.
Note that we use the `all` extra for testing.
This was missed in PR:
- #300
=> Add mlx-lm to all extra

src/smolagents/gradio_ui.py
Fix Gradio UI for None name.
Fix:
- #812
=> Fix Gradio UI for None name

src/smolagents/utils.py, tests/test_utils.py
Fixed regression introduced here: https://github.com/huggingface/smolagents/commit/e432d4190d36296456b62f358359be3bc184be34#diff-ff15ad77f081712933e506e9c4c618d724925b2a21bf3eb7ec49abeeeaeb49e6R150-R152
=> Fix json parsing

src/smolagents/agents.py
=> Sort additional authorized imports

src/smolagents/agents.py, src/smolagents/memory.py, src/smolagents/prompts/code_agent.yaml, src/smolagents/prompts/toolcalling_agent.yaml, tests/test_agents.py, tests/test_memory.py
This PR reduces the planning step to only one LLM call.
=> Reduce model calls in planning_step from 2 to 1

pyproject.toml, tests/test_agents.py, tests/test_default_tools.py, tests/test_final_answer.py, tests/test_models.py, tests/test_search.py, tests/test_tools.py, tests/test_types.py
Use `pytest-datadir` for shared data files.
=> Use pytest-datadir for shared data files

src/smolagents/agents.py
=> Refactor Agent.to_dict

pyproject.toml
Hotfix CI: pin transformers < 4.50.0
Close #1043.
=> Hotfix CI: pin transformers < 4.50.0

src/smolagents/tools.py, src/smolagents/utils.py
Align name of tool `__source__`.
=> Align name of tool __source__

src/smolagents/agents.py, src/smolagents/tools.py
Update type hints and docstrings of Agent/Tool .save with Path type.
=> Update type hints and docstrings of Agent/Tool .save with Path type

src/smolagents/models.py
Improve `MLXModel` call.
This PR simplifies the code by removing unnecessary variable and improving readability.
Follow-up to:
- #1059
=> Improve MLXModel call

pyproject.toml, src/smolagents/models.py, tests/test_cli.py, tests/test_models.py
Support transformers 4.50.0.
Simple hotfix, so users can use latest transformers release with support for Gemma 3.
Fix #1045.
=> Support transformers 4.50.0

docs/source/en/tutorials/secure_code_execution.mdx
We have advanced a lot on securing code execution through sandboxes: time to add more detail in the documntation!
=> Add detail on potential threats to system

src/smolagents/tools.py, tests/test_utils.py
Refactor `Tool.save`.
Follow-up to PR:
- #1051
=> Refactor Tool.save

docs/source/en/tutorials/tools.mdx
Add security disclaimer to MCP docs.
Fix #1085.
=> Add security disclaimer to MCP docs

src/smolagents/models.py
Improve `ApiModel` and subclasses instantiation:
- commmon params are set in the parent class
- client is created by calling `create_client`
=> Improve ApiModel and subclasses instantiation

src/smolagents/memory.py, tests/test_memory.py
Fixes https://github.com/huggingface/smolagents/issues/1097
=> Add user message after plan

docs/source/en/guided_tour.mdx, docs/source/en/tutorials/secure_code_execution.mdx, src/smolagents/agents.py, tests/test_agents.py
Addresses https://github.com/huggingface/smolagents/issues/1084
=> Add agent interruption

docs/source/en/conceptual_guides/intro_agents.mdx
Adds Code Agents in the agency table
=> Docs: Add Code Agents in agency table

README.md, docs/source/en/guided_tour.mdx, docs/source/en/reference/models.mdx, pyproject.toml, src/smolagents/models.py, tests/test_models.py
Closes #1092 
This pull request introduces the new `AmazonBedrockServerModel` class that provides direct access to Amazon Bedrock's foundation models via the Bedrock API. The implementation leverages the Bedrock `converse` API endpoint, allowing users to interact with all available Bedrock models through a consistent interface while maintaining the flexibility to configure model-specific parameters.
- Created `AmazonBedrockServerModel` class that extends `ApiModel`
- Implemented support for the Bedrock Runtime `converse` API
- Added flexible boto3 client configuration:
- Users can provide their own pre-configured boto3 client
- Default client creation with standard configurations when not provided
- Added comprehensive parameter handling:
- Model-specific inference configurations …
=> feat(models): add support for Amazon Bedrock native API

src/smolagents/agents.py, tests/test_agents.py, tests/test_monitoring.py
=> Fix memory step model output in ToolCallingAgent

examples/open_deep_research/scripts/text_inspector_tool.py
Make TextInspectorTool serializable.
Fix #1162.
=> Make TextInspectorTool serializable

src/smolagents/agents.py, src/smolagents/monitoring.py, tests/test_agents.py, tests/test_remote_executors.py
Introducing the DI for the logger as per: https://github.com/huggingface/smolagents/pull/1156#issuecomment-2790081091
=> Provide ability to override Agent logger

README.md, SECURITY.md
Add Security Policy.
Follow-up to:
- #1150
=> Add Security Policy

src/smolagents/agents.py
Improve docstring for stream run.
Close #1209.
=> Improve docs for stream run

src/smolagents/models.py, tests/test_models.py
Skip unsupported stop parameter for reasoning models.
Fix #1210.
=> Skip unsupported stop parameter for reasoning models

src/smolagents/agents.py, src/smolagents/models.py, src/smolagents/utils.py
Simplify validation of stream.
See:
- https://github.com/huggingface/smolagents/pull/1236#discussion_r2057730925
Follow-up to:
- #1236
=> Simplify validation of stream

src/smolagents/agents.py
Remove dead code related to non-CompletionDelta streaming results.
Follow-up to:
- #1236
=> Remove dead code related to non-CompletionDelta streaming results

src/smolagents/default_tools.py
=> Allow VisitWebpageTool to run on remote executors without installing smolagents

docs/source/en/_toctree.yml, docs/source/en/installation.mdx
Add Installation docs, explaining all optional installation extras.
=> Add Installation docs

src/smolagents/_function_type_hints_utils.py, tests/test_function_type_hints_utils.py, tests/test_tools.py
Support tools with union type return.
Fix #1277.
=> Support tools with union type return

docs/source/en/_toctree.yml, docs/source/en/examples/using_different_models.mdx
Add docs about Using different models.
In particular, add docs about using Gemini models.
See discussion in:
- https://github.com/huggingface/smolagents/pull/1279#pullrequestreview-2811363406
=> Add docs about Using different models: Gemini models

src/smolagents/default_tools.py
Implement SimpleWebSearchTool without 3rd-party dependencies:
- I used `HTMLParser`, that is a little verbose
Close #1295
Currently, it uses DuckDuckGo search provider, but it could be extended to use Bing (and others).
The name could also be:
- StandaloneWebSearchTool
- NativeWebSearchTool
- DefaultWebSearchTool
- LightweightWebSearchTool
CC: @aymeric-roucher 
Note that the anti-bot protection was not triggered during my tests using Colab (while it was triggered when testing locally).
=> Implement SimpleWebSearchTool

src/smolagents/local_python_executor.py, tests/test_agents.py
Support passing custom functions to local Python executor.
Fix #1301.
=> Support passing custom functions to local Python executor

src/smolagents/gradio_ui.py, tests/test_gradio_ui.py, tests/test_monitoring.py
Fix duplicate error message in GradioUI, test, and refactor.
Fix:
- Before, error message was raised twice:
https://github.com/huggingface/smolagents/blob/d8db112be8f208db851c0836d56de0c9b157cd6d/src/smolagents/gradio_ui.py#L115-L121
https://github.com/huggingface/smolagents/blob/d8db112be8f208db851c0836d56de0c9b157cd6d/src/smolagents/gradio_ui.py#L133-L137
=> Fix duplicate error message in GradioUI, test, and refactor

src/smolagents/vision_web_browser.py
Implements Issue #1332 
I'm not sure which branch to merge into, so please advise!
=> Enable local web agents via api_base and api_key

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Revert "Add timeout mechanism for code execution".
Issue reported in:
- #1339
=> Revert "Add timeout mechanism for code execution"

tests/test_local_python_executor.py
Refactor tests of `LocalPythonExecutor`.
=> Refactor tests of LocalPythonExecutor

docs/source/en/examples/text_to_sql.mdx
Edit Llama model name from Meta-Llama-[...] to Llama-[...]
=> Fix Llama model name in docs example

docs/source/en/tutorials/tools.mdx, pyproject.toml, src/smolagents/mcp_client.py, src/smolagents/tools.py, tests/test_tools.py
Support Streamable HTTP MCP servers.
Close #1354.
=> Support Streamable HTTP MCP servers

src/smolagents/agents.py, tests/test_agents.py
Make Agent.system_prompt read only.
=> Make Agent.system_prompt read only

src/smolagents/default_tools.py
Create API web search tool.
Close #1395.
=> Create API web search tool

docs/source/en/tutorials/secure_code_execution.mdx
Quick copy&paste mistake: E2B -> Docker
=> Fix typo in secure code execution documentation

src/smolagents/agents.py, tests/fixtures/tools.py, tests/test_agents.py
This PR implements:
- Support multiple tool calls in ToolCallingAgent
- Call them in parallel
=> Support multiple tool calls in parallel in ToolCallingAgent

examples/server/README.md, examples/server/main.py
Add chat server demo to examples.
TODO:
=> Add chat server demo to examples

src/smolagents/default_tools.py
Support custom headers/params for ApiWebSearchTool.
=> Support custom headers/params for ApiWebSearchTool

src/smolagents/gradio_ui.py, src/smolagents/models.py, tests/test_agents.py, tests/test_models.py, tests/test_monitoring.py
Update usage in gradio_ui and tests.
=> fix(ChatMessage): set type `role: MessageRole`.

src/smolagents/agents.py, src/smolagents/local_python_executor.py, src/smolagents/remote_executors.py, tests/test_cli.py, tests/test_local_python_executor.py, tests/test_remote_executors.py
Implement CodeOutput as analog to ToolOutput, after the merge of:
- #1482
=> Implement CodeOutput as analog to ToolOutput

src/smolagents/default_tools.py
Implement rate limit mechanism in `DuckDuckGoSearchTool`.
Follow-up to:
- #1508 
Fix #1501.
=> Implement rate limit mechanism in DuckDuckGoSearchTool

docs/source/en/reference/tools.md, src/smolagents/default_tools.py
Explain `rate_limit` in tools docstrings:
- DuckDuckGoSearchTool
- ApiWebSearchTool
=> Explain rate_limit in tools docstrings

docs/source/en/installation.md
Improve Installation docs with `uv` option.
=> Improve Installation docs with uv option

CONTRIBUTING.md
Add `uv` option to CONTRIBUTING.
=> Add uv option to CONTRIBUTING

src/smolagents/agents.py, src/smolagents/utils.py, tests/test_utils.py
Factorize `create_agent_gradio_app_template` function.
=> Factorize create_agent_gradio_app_template function

docs/source/en/_toctree.yml, docs/source/en/conceptual_guides/intro_agents.md
I propose to update this page's title, to make it more appealing to readers, especially people coming from google.
=> Update title of page "What are agents"

.github/workflows/build_documentation.yml
=> Enable multilingual docs

src/smolagents/agents.py
Remove deprecated agent logs attribute.
=> Remove deprecated agent logs attribute

src/smolagents/models.py
Fix missing kwargs forward to vLLM model generate call.
=> Fix missing kwargs forward to vLLM model generate call

tests/test_telemetry.py
Test telemetry extra.
This PR will help catch future breakage before releases, allowing to proactively fix issues in the OpenInference library or coordinate releases properly.
Follow-up to:
- #1699
=> Test telemetry extra

docs/source/ko/_toctree.yml, docs/source/ko/examples/multiagents.md
Translated the `multiagents.md` file of the documentation to Korean.
Thank you in advance for your review.
Part of https://github.com/huggingface/transformers/issues/20179
- [] Check live-preview for gotchas (live-preview로 정상작동 확인)
May you please review this PR?
@4N3MONE, @yijun-lee, @jungnerd , @harheem
[@songi104](https://github.com/songi104), [@chhaewxn](https://github.com/chhaewxn), [@AhnJoonSung](https://github.com/AhnJoonSung), [@jihyun-0611](https://github.com/jihyun-0611), [@seopp](https://github.com/seopp)
Pull Request section?
to it if that's the case.
[documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
[here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation). …
=> 🌐 [i18n-KO] Translated `multiagents.md` to Korean

.gitignore, pyproject.toml, src/smolagents/remote_executors.py, tests/test_remote_executors.py
fixes #1744 
I believe that's the only modification necessary.
right?
=> Support e2b-code-interpreter v2

docs/source/ko/_toctree.yml, docs/source/ko/reference/models.md
Translated the `models.md` file of the documentation to Korean.
Thank you in advance for your review.
Part of https://github.com/huggingface/smolagents/issues/1607
May you please review this PR?
@AhnJoonSung, @nsbg, @yijun-lee, @FacerAin, @Judy-Choi, @HyunZ118, @jungnerd
Pull Request section?
to it if that's the case.
[documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
[here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
@albertvillanova May you please review this PR?
=> 🌐 [i18n-KO] Translated `models.md` to Korean 
