huggingface/smolagents

docs/source/en/tutorials/building_good_agents.md
Really enjoying this library, great work! I fixed some minor spelling errors in the "building good agents" tutorial documentation while I was reading through it. Below is a summary of the changes made:
---
1. **Line 29:**  
-  `introducessome` → `introduces some` 
2. **Line 31:**  
-  `worklow` → `workflow` 
3. **Line 34:**  
-  `functions` → `function` 
4. **Line 171:**  
-  `tid` → `did` 
5. **Line 182:**  
-  `claritications` → `clarifications`
=> Fixing minor spelling errors in building_good_agents.md

README.md, src/smolagents/models.py
This PR introduces the `device` parameter to the `TransformersModel` class, allowing users to explicitly specify the device (`"cpu"`, `"cuda"`, etc.) for model loading and inference. This change improves flexibility and control over model deployment environments, especially when running on systems with mixed hardware setups.
1. **Device Detection**:
- Added logic to automatically detect and set the device (`cuda` if available, otherwise `cpu`).
- Modified the model instantiation and data tensor operations to respect the detected device.
- Added a `to(device)` call to move the model and tensors to the appropriate device.
2. **Backward Compatibility**:
- No breaking changes introduced. If the device is not specified, the script defaults to the best available option.
3. **Enhance Logging**: …
=> Add device parameter for TransformerModel in models.py

src/smolagents/tools.py
I was not able to use the base ToolCollection from huggingface/smolagents : it would error on trust_remote_code from the Tool.from_hub call . 
I'm adding those parameters (trust_remote_code and token) to the constructor.
HuggingFace online documentation still needs to be updated as it imports the wrong  ToolCollection (from transformers, not smolagents)
=> fix ToolCollection usage 

examples/ddg_leopard.py, src/smolagents/default_tools.py
You can now optionally pass `max_results` into the `DuckDuckGoSearchTool`. Default behavior is unchanged (10 results).
```python
DuckDuckGoSearchTool(max_results=2)
```
Test with `examples/ddg_leopard.py`
=> feat: Add max_results kwarg to DDGS tool

docs/source/en/examples/rag.md
As per the title, one of the needed libraries for this example was not included in the first step, where you install the required libraries using pip. 
This PR simply adds that library to the pip install list :)
=> Include missing pip install library in RAG example

docs/source/en/examples/rag.md
Missing verb in “The agent can the generated snippets ...”
Original:
“The agent can the generated snippets and re-retrieve if needed, as in Self-Query.”
Fix:
“The agent can use the generated snippets and re-retrieve if needed, as in Self-Query.”
=> Update rag.md with missing verb

src/smolagents/gradio_ui.py
Some minor tweaks and suggestions for the gradio demo:
* The `content` of a gradio chat message cannot be None. I was running into errors when the code agent was setting the llm_output was None.
* Wrapping the observations in "```" blocks would not display the observation as markdown. By removing this, we can display the output as markdown which makes links interactive and respects the LLM format.
For example,
vs
=> Small tweaks to Gradio demo

docs/source/en/examples/multiagents.md
Just a small fix to spelling and grammar to the query in multiagents.md file . 
The original query was:
```
"If LLM trainings continue to scale up at the current rhythm until 2030, what would be the electric power in GW required to power the biggest training runs by 2030? What does that correspond to, compared to some contries? Please provide a source for any number used."
```
The modified query is:
```
"If LLM training continues to scale up at the current rhythm until 2030, what would be the electric power in GW required to power the biggest training runs by 2030? What would that correspond to, compared to some countries? Please provide a source for any numbers used."
```
=> Fixing spelling and grammar for query

docs/source/en/tutorials/building_good_agents.md, docs/source/en/tutorials/secure_code_execution.md, docs/source/en/tutorials/tools.md
Fix Spelling Errors in Documentation**
This PR corrects minor spelling errors across three documentation files: `tools.md`, `secure_code_execution.md`, and `building_good_agents.md`.
---
1. Line 92: Corrected `method` → `methods`.
2. Line 93: Corrected `directky` → `directly`.
3. Line 213: Corrected `you` → `your`.
1. Line 50: Corrected `Wev'e` → `We've`.
1. Line 236: Corrected `yo` → `you`.
2. Line 238: Corrected `promptmust` → `prompt must`.
---
These changes address minor spelling issues to enhance the documentation's clarity, readability, and professionalism.
---
=> Fix Spelling Errors in Documentation

pyproject.toml, src/smolagents/models.py
This PR implements a new model type, OpenAIServerModel, which is compatible with any server host using an OpenAI compatible API without having to introduce LiteLLM as a middleware dependency.
This PR closes #96 
Example implementation, tested with LM Studio:
```python
from smolagents import CodeAgent, DuckDuckGoSearchTool, OpenAIServerModel
def test_openai_compatible():
agent = CodeAgent(
tools=[DuckDuckGoSearchTool()],
model=OpenAIServerModel(
model_id="qwen2.5-coder-32b-instruct",  # or whatever model ID your server uses
api_base="http://localhost:1234/v1",  # replace with your server URL
api_key="lm-studio",  # replace with your API key
temperature=0.7
)
)
query = "How many seconds would it take for a leopard at full speed to run through Pont des Arts?"
result = agent.run(query) …
```
=> Implement OpenAIServerModel

.github/workflows/quality.yml, docs/source/en/examples/multiagents.md, docs/source/en/tutorials/tools.md, pyproject.toml, src/smolagents/default_tools.py, src/smolagents/models.py, src/smolagents/tools.py, src/smolagents/types.py, tests/test_types.py
Issue raised by @xianminx: https://github.com/huggingface/smolagents/issues/100
This PR removes torch dependency to make install and imports faster.
Tested on this script:
```py
import time
t0 = time.time()
from smolagents import CodeAgent, HfApiModel
t1 = time.time()
print(f"Total time: {t1 - t0:.2f}")
```
The runtime falls from 6.52s to 3.8s, nearly halved!
=> Halve import time by removing torch dependency

src/smolagents/models.py
**Summary**:
Previously, in the `TransformersModel` class of smolagents, the model was allocated to a device using `.to(device)`, which limited usage to only one CUDA card. This commit addresses that limitation by introducing the option to use `device_map='auto'` for better utilization of multiple GPUs.
**Problem Addressed**:
- **Limited GPU Utilization**: smolagents could only use a single CUDA device before, restricting performance for large models that could benefit from parallel processing across multiple GPUs. For instance, running large language models for text generation tasks was slower than it could be with multiple GPUs.
- **Lack of Scalability**: As model sizes and task complexity grew, the existing `.to(device)` method didn't offer the necessary scalability. Additionally, an …
=> feat: Add multi-GPU support for TransformersModel

src/smolagents/local_python_executor.py, tests/test_python_interpreter.py
fix for #181.
btw:
```python
elif name.id in custom_tools:
return custom_tools[name.id]
```
to allow a list of objects, like : 
```python
def my_func():
do_smth()
list = [my_func, my_func] 
```
Now we get the error: 
**The variable `my_func` is not defined.**
=> The call.func parameter type of the local_python_executor.evaluate_call function might be ast.Subscript 

docs/source/en/tutorials/building_good_agents.md
function get_coordinates_from_location should be actually convert_location_to_coordinates
=> fix typo in building_good_agents.md

examples/benchmark.ipynb
Fix vanilla model answer in example benchmark, by returning `ChatMessage.content` instead of `ChatMessage`:
- Return: `"answer": "80"`
- Instead of: `"answer": "ChatMessage(role='assistant', content='80', tool_calls=None)"`
=> Fix vanilla model answer in example benchmark

examples/gradio_upload.py, src/smolagents/gradio_ui.py
With the release of v1.3.0, file upload errors (such as uploading a disallowed type) result in the following exception:
```
ValueError: A  function (upload_file) didn't return enough output values (needed: 2, returned: 1).
Output components:
[textbox, state]
Output values returned:
["File type disallowed"]
```
This PR introduces the correct return values on error. Also upped verbosity in the example and remove the height=1 parameter so the box renders better in the browser :^).
=> Return textboxes on Gradio file upload errors

docs/source/en/tutorials/tools.md
Love your work! I am going to fix a couple of bugs in the docs to get going, here is the first one 🤗
The current example for generating an image with an improved prompt fails with:
"TypeError: MultiStepAgent.run() got an unexpected keyword argument 'prompt'" (both in 1.3.0 and the version before)
Seems like the way to pass additional args was changed to use a dict with the name additional_args. Looked it up in the code, changed it accordingly, tested it, works. 
I have also included a hint to the additional_args option in the text and renamed 'prompt' to 'user_prompt' to make the example easier to understand.
=> Docs Bug - fix tool example with additional args

docs/source/en/examples/multiagents.md, docs/source/zh/examples/multiagents.md
All default agents seem to have been moved to one and the same file now.
I changed the English md file as well as the Chinese one. I included lines 151 to 176. Do we want to keep it that way or just reference the file since the lines might get changed often?
Also, I see there is a diff for line 199 for some reason. I didn't change it, but maybe it's due to new line formatting for different computers?
=> Dead Link to Duck Duck Go search tool

src/smolagents/gradio_ui.py
A small change with huge impact. Allows the user of the Chat UI to resize the chat box. This is especially helpful when the Agent creates long outputs and there is screen estate left.
=> Add resizeable option to Gradio UI component for better usabilty

src/smolagents/agents.py, tests/test_agents.py
Should resolve #223 , I went with removing `self.initialize_system_prompt()` from the step method, as it is already called in `__init__`. Although there may be side effects of not including this in `agent.run()` ?
=> Fix missing python modules in CodeAgent system prompt

pyproject.toml, src/smolagents/models.py
Make `openai` dependency optional.
I think we could reduce the required dependencies upon installation of `smolagents` to some minimal set, and set all the other dependencies as optional:
- `openai` dependency could be made an optional dependency: only required if the user wants to use `OpenAIServerModel`
- I could also set other dependencies as optional
- eventually, we could provide some easy way to install optional dependencies by using extras
- EDIT: In the line with this PR by @Wauplin (I just saw it)
- #229
Let me know what you think, @aymeric-roucher.
=> Make openai dependency optional

src/smolagents/models.py, src/smolagents/types.py, src/smolagents/utils.py, tests/test_types.py
Remove dependency on `_is_package_available` from `transformers`.
I think it makes no sense to depend on the `transformers` library for this package management utility.
=> Remove dependency on _is_package_available from transformers

docs/source/en/guided_tour.md, docs/source/en/tutorials/tools.md
Make smolagents useable with ollama: The ollama default context length is 2048 which is way to little for tasks involving more than 1 step. Fails horribly and the CodingAgent tends to start calculating the age of the pope as a second step - if you haven't read the system prompts this will be a very weird experience 😂.
Adding this important hint in the docs will help many people getting started with local agents.
=> Set ollama context lenght in example to 8192 to make it work

docs/source/zh/examples/multiagents.md
This PR relates to https://github.com/huggingface/smolagents/issues/141. More translations are coming in other PR and this one is ready for review now. Thanks!
=> Add Chinese translations for multi-agent example

src/smolagents/utils.py
Better handling `Console` size based on current terminal setup, no need to be fixed to 200
=> chore: unset console width, utilize auto detect feature

src/smolagents/agents.py, src/smolagents/local_python_executor.py, src/smolagents/utils.py
The default limit for print outputs is 50000 characters. In some use cases, this limit is too high, and it is causing high token counts and costs.
This PR proposes to make it a parameter of LocalPythonInterpreter and CodeAgent.
Moreover, this PR contains 2 bug fixes to make it work properly:
- Fixing incorrect `truncate_content` behavior
- Deleting unused `truncate_print_outputs` function
=> Max length of "print" outputs as a parameter of an agent

docs/source/en/guided_tour.md, src/smolagents/tools.py
Two very minor fixes: 
- one example in the docs requires `trust_remote_code=True` to run correctly
- a small formatting update in the docstrings
=> docs: small fixes in docs

src/smolagents/agents.py
Implementing an own Model class I noticed that the type annotations of the Agent constructors were not correct and consistent.
This PR makes the type annotations consistent with the new Model `__call__` signature across all Agent classes.
=> refactor: update model type to ChatMessage in agent classes

src/smolagents/gradio_ui.py, tests/test_monitoring.py
This `test_mode` parameter seems more of a legacy parameter from the `transformers` codebase. Removing it is a breaking change but I do think that removing it quickly is for the best (I doubt it's being used anywhere).
=> Remove unused and undocumented `test_mode` parameter

src/smolagents/tools.py
The `from_langchain` Tool example in the docs failed, because the implementation in the `LangChainToolWrapper` class did not skip the input validation (as implemented for `SpaceToolWrapper` and `PipelineTool`), so depending on the actual langchain tool spec it would fail. 
The langchain example in the "Tools - in depth guide" section currently yields:
_Exception: Tool's 'forward' method should take 'self' as its first argument, then its next arguments should match the keys of tool attribute 'inputs'._
After fixing this, the `LangChainToolWrapper` still failed because the `self.is_initialized` attribute was not set to `True` at the end of `__init__`. Also fixed. Should a from_langchain tool require longer loading of models etc, you could subclass it and implement a different behaviour in …
=> Fix Bug in from_langchain in tools.py

src/smolagents/local_python_executor.py, tests/test_python_interpreter.py
cc @NeuralNotwerk: this improve the usage of close matches in mappings to make them suggestions in the error message instead of automatically picking the closest match!
=> Python interpreter: improve suggestions for possible mappings

src/smolagents/local_python_executor.py, tests/test_python_interpreter.py
Some builtins functions contain an attribute (```__self__```) that refers to the builtins module itself. It can then be used in order to invoke compile and exec in order to execute arbitrary code.
=> The use of BASE_PYTHON_TOOLS enables the use of compile, exec and eval

src/smolagents/local_python_executor.py, tests/test_python_interpreter.py
Try first dunder method in `evaluate_augassign`.
In `x += 1` expression:
- If `x` has an `__iadd__` method, use it. 
- Otherwise, use `x = x + 1`.
Fix #190.
=> Try first dunder method in evaluate_augassign

pyproject.toml
Add `huggingface-hub` as required dependency.
Fix #289.
CC: @Wauplin
=> Add huggingface-hub as required dependency

src/smolagents/e2b_executor.py
Remove `pickle5` package from E2BExecutor.
The `pickle5` package is only necessary for Python 3.5, 3.6 and 3.7, but `smolagents` requires Python >= 3.10.
=> Remove pickle5 package from E2BExecutor

README.md, docs/source/en/index.md
- Changed the description of Hub integrations to specify the sharing and loading of Gradio Spaces as tools.
- Fixed a formatting issue in the code snippet by removing an extraneous comma in the import statement.
=> Update README and documentation to clarify Hub integrations with Gradio Spaces

src/smolagents/agents.py, src/smolagents/utils.py, tests/test_agents.py, tests/test_monitoring.py
if this isn't correct, just close the PR.
=> minor fix for console in AgentLogger

docs/source/en/guided_tour.md, docs/source/en/reference/agents.md, src/smolagents/models.py
Adds Azure OpenAI support as per #276.
There are some small differences from my initial proposal, the main one being renaming `model_id` to `model`. 
Imo using `model_id` doesn't make sense for Azure OpenAI, the `openai` package uses `model` as well, and in Azure this field refers to a model deployment. 
I can rename this to `model_id` for consistency purposes with the other `Model` implementations if needed, but I think it would be confusing for Azure users.
Other than that, I've also fixed some small issues with the original OpenAIServerModel docs, hope it's ok.
=> Add Azure OpenAI support

src/smolagents/local_python_executor.py
#274  blocked eval, compile and exec from being invoked through the ```__self__```attribute, but there are several other functions in ```builtins``` that may be dangerous (for instance ```breakpoint```, ```open```, ```__import__```). This PR would prevent any ```builtins``` function from being invoked if it has not been explicitely added as a tool.
=> Local interpreter security: prevent builtins functions from being used if they have not been added as tools

src/smolagents/default_tools.py
Some site may be unresponsive and leave the agent hanging for a while. Adding a 60 seconds time cutoff for the request to url to conclude in the visit_webpage tool
=> Minor fix: adding a 60 seconds timeout to the visit webpage tool

pyproject.toml, src/smolagents/tool_validation.py, src/smolagents/tools.py, src/smolagents/utils.py, tests/test_utils.py
Hi 👋 This is my first contribution to smolagents, hope this helps!
This PR fixes source code inspection in interactive shells (IPython, Jupyter). Currently, using smolagents in these environments results in an `OSError` when `inspect.getsource` tries to find a source file that doesn't exist in interactive sessions.
The solution:
- Get code from current shell session
- Parse it using `ast`
- Walk through to find matching class/function definitions
Fixes #250 by @MoritzLaurer
Changes:
- Added source code extraction from IPython shells
- Added unit tests
- Added `ipython` as test dependency
- Nit: clean the source code as well (dedent & strip)
Tested in ipython & jupyter lab environments, as well as using a standard python invocation.
Tests & Lint seem to pass as well.
I'd be happy to add …
=> Fix: source code inspection in interactive shells

src/smolagents/local_python_executor.py, tests/test_python_interpreter.py
Refactor `evaluate_augassign` and test all operators.
This PR refactors the code (by making it simpler and equivalent) introduced by:
- #285
=> Refactor evaluate_augassign and test all operators

src/smolagents/local_python_executor.py
Create a copy of static_tools to avoid modifying the original object.
=> Improve static tools initialization safety

src/smolagents/agents.py
Rename `tool_response_message` to `error_message` and append it to `messages`.
Currently, the variable `tool_response_message` in this conditional statement is not used: https://github.com/huggingface/smolagents/blob/fe2f4e735caae669949dae31905756ad70fcf63e/src/smolagents/agents.py#L291-L301
See related discussion in:
- https://github.com/huggingface/smolagents/pull/220#discussion_r1925897201
=> Append unused error message to memory

pyproject.toml
With `torchvision` being made a requirement, installing `smolagents` doesn't feel like installing something "smol". `torch` is an extra and `torchvision` should be put there too.
=> Move torchvision to the torch extra

src/smolagents/agents.py
Add args to `ToolCallingAgent ``CodeAgent `and `ManagedAgent `docstring.
=> docstring args for ToolCallingAgent, CodeAgent and ManagedAgent

src/smolagents/prompts.py
This is to close the remaining part of #264 until the general prompt refactoring is done. It prevents occasional problems with the tool call format. The main issue was closed in #318
=> Corrected tool examples in ToolCallingAgent system prompts

src/smolagents/models.py
Use transformers as optional dependency.
Transformers is now an optional dependency, but we made a regression and we require it at import time as a required dependency. This raises a `ModuleNotFoundError` when smolagents is installed with no extra.
This PR fixes the use of transformers, as an optional dependency.
I think we need to make a patch release.
Fix #357.
CC: @aymeric-roucher
=> Use transformers as optional dependency

docs/source/en/examples/rag.md
datasets is used in the code later and would throw an error
in the below code: 
```python
import datasets
from langchain.docstore.document import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.retrievers import BM25Retriever
knowledge_base = datasets.load_dataset("m-ric/huggingface_doc", split="train")
knowledge_base = knowledge_base.filter(lambda row: row["source"].startswith("huggingface/transformers"))
source_docs = [
Document(page_content=doc["text"], metadata={"source": doc["source"].split("/")[1]})
for doc in knowledge_base
]
text_splitter = RecursiveCharacterTextSplitter(
chunk_size=500,
chunk_overlap=50,
add_start_index=True,
strip_whitespace=True,
separators=["\n\n", "\n", ".", " ", ""],
)
docs_processed = …
```
=> Add pip install datasets to RAG example

src/smolagents/agents.py, src/smolagents/prompts.py
Code snippet to reproduce the bug:
```python
from smolagents import load_tool, CodeAgent, HfApiModel, DuckDuckGoSearchTool
image_generation_tool = load_tool("m-ric/text-to-image", trust_remote_code=True)
search_tool = DuckDuckGoSearchTool()
agent = CodeAgent(
tools=[search_tool, image_generation_tool],
model=HfApiModel("Qwen/Qwen2.5-Coder-32B-Instruct"),
planning_interval=2 # This is where you activate planning!
)
result = agent.run(
"How long would a cheetah at full speed take to run the length of Pont Alexandre III?",
)
```
Traceback:
```
[/usr/local/lib/python3.11/dist-packages/smolagents/models.py](https://localhost:8080/#) in get_clean_message_list(message_list, role_conversions, convert_images_to_image_urls, flatten_messages_as_text)
227 …
```
=> Fix Extra planning

src/smolagents/types.py
Correct the conditional checks in the `AgentAudio` class by invoking the `is_torch_available` function. This prevents unintended `ImportError` when `torch` is not installed.
* (typo) issue resolved: The `is_torch_available` function was referenced without parentheses, causing it to be treated as a variable rather than being executed. This led to incorrect evaluation of the condition and potential `ImportError` when `torch` is unavailable.
=> chore: Fix Typo by Calling is_torch_available() in AgentAudio Class

src/smolagents/models.py
=> Additional parameters for openai client

src/smolagents/default_tools.py
Add ddgs_kwargs parameter to constructor for flexible configuration.
This could be useful when users need to customize DDGS.
```python
tool = DuckDuckGoSearchTool(
ddgs_kwargs={
'timeout': 20,
'proxies': 'socks5h://localhost:9050',
'headers': {'User-Agent': 'my-custom-agent'}
}
)
```
=> DuckDuckGoSearchTool: add ddgs_kwargs parameter to constructor

src/smolagents/e2b_executor.py, src/smolagents/tool_validation.py
* Closes #244 
* I'm not sure if this is the best fix. Please review and suggest any improvements.
**Additional Context:**
* While working on the fix, I encountered an installation issue with the current PyPI release on smolagents on e2b.
* I tested the changes by removing torchvision and transformers which allowed the package to be installed successfully.
=> Fix final_answer issue in e2b_executor

docs/source/en/examples/text_to_sql.md
1. Fix name to waiters for second table
2. Remove incorrect comment
3. Dedupe insert row logic - it's not central to the example so shouldn't be repeated
Thanks for the library, it looks great so far.
If not useful, happy to iterate, or feel free to close the PR and fix this up a different way
=> Docs: Text to sql example - minor naming / dedupe

src/smolagents/local_python_executor.py, tests/test_python_interpreter.py
Context:
Import of `os` was failing because os was recognized as a dangerous pattern, even when the import from os was explicitly authorized under `additional_authorized_imports`: this PR fixes this.
=> Fix blocking of os in authorized imports

pyproject.toml
We just released a patch `5.13.2` with the key change being that consecutive chatbot messages with or without tool usage are rendered more nicely (https://github.com/gradio-app/gradio/pull/10448#issuecomment-2619901524)
=> Update minimum Gradio version

examples/agent_from_any_llm.py
Again setting the num_ctx higher than the default 2048 is important,otherwise after more than 2 steps it will start to look for the age of the pope no matter what 😂
And minor error in the las print message which prints the wrong agent.
=> Minor fix for agent_from_any_llm.py example

docs/source/en/examples/rag.md
model=HfApiModel("meta-llama/Llama-3.3-70B-Instruct")  throws an error as it's only available with the Pro subscription and it's not easy to find which models are available for free. 
Not passing an argument seems like the easiest solution for now.
=> Remove explicit model arg in HfApiModel - which wouldn't run without Pro

src/smolagents/memory.py, tests/test_memory.py
Fix and test MemoryStep.
Note:
- .dict method was raising: TypeError: asdict() should be called on dataclass instances
- .raw attribute is never used
- Why was this attribute added? CC: @clefourrier @aymeric-roucher 
TODO:
=> Fix and test MemoryStep

pyproject.toml, src/smolagents/local_python_executor.py, tests/test_python_interpreter.py
Fixes https://github.com/huggingface/smolagents/issues/339 and fixes https://github.com/huggingface/smolagents/issues/291
The current `get_safe_module` eagerly imports dynamic & lazy imports, even unwanted ones.
One way to solve this issue is to wrap the `getattr` with a `try... except ImportError` and log.
Another way, less agressive, is to use `__dict__` instead of `dir` so that to not import dynamically added modules.. at the cost of missing dynamically added modules.
One can test the following, using uv:  
```bash
echo '# /// script
import smolagents
interpreter = smolagents.LocalPythonInterpreter(additional_authorized_imports=["matplotlib"], tools={})
interpreter("import matplotlib.pyplot as plt", {})' | uv run -
```
You are free to read per commit!
Thanks for reviewing …
=> Fix get safe module

src/smolagents/agents.py
Remove duplicated `final_memory_step` creation.
It was created twice:
- First, with `step_number=self.step_number`
- Second, with `step_number=None`
I kept the first one.
=> Remove duplicate final_memory_step creation

src/smolagents/models.py
Remove unused `ChatMessageToolCall` raw argument.
Again, contrary to `ChatMessage.raw`, `ChatMessageToolCall` has no `raw` attribute, and therefore it makes no sense to pass the `raw` argument to its class method: the `raw` argument was ignored.
See similar issue with `MemoryStep.raw`:
- #432
=> Remove unused ChatMessageToolCall raw argument

src/smolagents/agents.py, src/smolagents/local_python_executor.py, src/smolagents/memory.py, src/smolagents/models.py, tests/test_agents.py, tests/test_memory.py
@albertvillanova this is a small fix: until now in case of error, print outputs were not shown to the user or to the agent. Now this is fixed and tested.
=> Improve code execution logs in case of error by showing print outputs

src/smolagents/models.py
the current `TransformersModel` docstring seems to be a duplicate of `HfApiModel`.
=> Fix TransformersModel docstring

src/smolagents/models.py
Remove default max_tokens for all models.
Fix #468.
=> Remove default max_tokens for all models

src/smolagents/tools.py
Fixed issue where passing the token directly in the `push_to_hub` function was not working.
=> Minor Fix tool push_to_hub

src/smolagents/agents.py, tests/test_agents.py
Currently, trying to run an agent with `single_step=True` and telemetry enabled causes an error: `AttributeError: 'ToolCallingAgent' object has no attribute 'step_number'`.
It happens because `step_number` is not initialized when `single_step=True` and the instrumentor tries to access it [here](https://github.com/Arize-ai/openinference/blob/2d93f4850df963394c3d7182a86f51b30924f167/python/instrumentation/openinference-instrumentation-smolagents/src/openinference/instrumentation/smolagents/_wrappers.py#L148).
This PR simply sets it explicitly in that case.
To repro:
```python
from smolagents import ToolCallingAgent, HfApiModel
from smolagents import VisitWebpageTool
from opentelemetry.sdk.trace import TracerProvider
from openinference.instrumentation.smolagents import SmolagentsInstrumentor …
```
=> Fix undefined `step_number` in single_step run

tests/conftest.py, tests/test_agents.py
Suppress terminal logging in CI tests.
The approached I followed: I set logger.level = -1 for CI tests.
Fix #503.
Agent tests:
- Before:
````
tests/test_agents.py::TestMultiStepAgent::test_logging_to_terminal_is_disabled FAILED
tests/test_agents.py::TestMultiStepAgent::test_step_number ╭────────────────────────────────── New run ───────────────────────────────────╮
│                                                                              │
│ Test task                                                                    │
│                                                                              │
╰─ MagicMock - <MagicMock name='mock.model_id' id='140456269450064'> ──────────╯
PASSED
tests/test_agents.py::TestMultiStepAgent::test_planning_step_first_step …
```
=> Suppress terminal logging in CI tests

docs/source/en/reference/tools.md
Added missing documentation for default tools (FinalAnswerTool, GoogleSearchTool, SpeechToTextTool).
=> Add missing default tools to reference docs

tests/test_models.py
Test HfApiModel call with custom_role_conversions.
The custom_role_conversions was introduced in HfApiModel by:
- #317
=> Test HfApiModel call with custom_role_conversions

src/smolagents/local_python_executor.py
Set MAX_WHILE_ITERATIONS as module variable.
This way, it can be customized by the users. See discussion: https://github.com/huggingface/smolagents/pull/317/files#r1941330052
=> Set MAX_WHILE_ITERATIONS as module variable

src/smolagents/e2b_executor.py
Hello, while trying e2b_executor example,
```
File "/Users/femtozheng/python-project/smolagents/src/smolagents/e2b_executor.py", line 48, in __init__
self.logger.log("Initializing E2B executor, hold on...")
^^^^^^^^^^^
AttributeError: 'E2BExecutor' object has no attribute 'logger'
python-BaseException
```
seemed pass in logger doesn't get set to self.logger,
so I added one.
=> add self.logger = logger for e2b_executor

src/smolagents/agents.py, src/smolagents/monitoring.py, tests/conftest.py
Support disabling logging to terminal, with `LogLevel.OFF`.
Use case: when the running is done for benchmarks/evaluations or tests, the user might want to disable logging to the terminal.
Related to:
- #504
=> Support disabling logging to terminal

pyproject.toml, src/smolagents/__init__.py, src/smolagents/agents.py, tests/test_import.py
Fix installation with data files: ModuleNotFoundError: No module named 'smolagents.prompts'
```python
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/runner/.cache/uv/builds-v0/.tmp1eGz4Z/lib/python3.10/site-packages/smolagents/__init__.py", line 28, in <module>
from .prompts import *
ModuleNotFoundError: No module named 'smolagents.prompts'
```
After PR:
- #502
=> Fix installation with data files

pyproject.toml
Pin openinference-instrumentation-smolagents >= 0.1.4 with fixes:
- https://github.com/Arize-ai/openinference/pull/1274
- https://github.com/Arize-ai/openinference/pull/1238
=> Pin openinference-instrumentation-smolagents >= 0.1.4

src/smolagents/agents.py, tests/test_agents.py
EDIT:
Remove unused `prompts_path` argument and use `prompt_templates` instead.
EDIT:
~~Use `prompt_path` argument, previously introduced but not used.~~
~~Remove unused `prompts_path` argument.~~
This argument was introduced (but not used) in:
- #502
Or maybe you wanted to use it somehow? @aymeric-roucher
=> Delete prompts_path argument and use prompt_templates

src/smolagents/agents.py
Fix deprecation warning from importlib.resources.read_text:
```
huggingface/smolagents/src/smolagents/agents.py:784: DeprecationWarning: read_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
importlib.resources.read_text("smolagents.prompts", "code_agent.yaml")
```
=> Fix deprecation warning from importlib.resources.read_text

.github/workflows/tests.yml, tests/test_e2b_executor.py
Test E2B Executor.
See, we had previously introduced a bug in its instantiation without noticing it due to the lack of tests:
- #537
=> Test E2B Executor

docs/source/en/conceptual_guides/intro_agents.md
=> Small update to 'Introduction to Agents' docs format

docs/source/en/tutorials/building_good_agents.md
Very small/simple nit fix where the right word to use should be "former" rather than "latter" as "latter" means the last in the list which here refers to a "bad agent".
=> Doc grammar fix

docs/source/en/conceptual_guides/intro_agents.md
Two small grammar correction in _Introduction to Agents_:
- "The figure [...] illustrate some advantages" should be "illustrate**s**"
- "plenty of [...] code actions" is plural so we use "are" in place of "is".
=> Minor grammar correction

src/smolagents/local_python_executor.py
Add the list of authorized imports to the `ast.ImportFrom` error message, bringing it in line with the error from `ast.Import`
=> Add authorized_imports in importFrom errors

src/smolagents/agents.py, tests/test_agents.py
Hello. I found something strange while reading the code to study.
The initial fact extraction process requires task information. But I couldn't find that code.
After looking up some history, I think this is a bug, so I suggest a patch.
Code from 8ba036bba0392b36b72d0e60e808cfe7e329b954
Fix #575
=> Restore missing user prompt for initial facts

examples/open_deep_research/README.md
In the readme, python is not executing the program run.py.  Added run.py to the command line call to fix this.
=> Fixed Readme that is missing run.py call

tests/test_models.py
Fix 429 Client Error: Too Many Requests for test_get_hfapi_message_no_tool: https://github.com/huggingface/smolagents/actions/runs/13258491319/job/37009590754?pr=499
```
=========================== short test summary info ============================
FAILED tests/test_models.py::ModelTests::test_get_hfapi_message_no_tool - huggingface_hub.errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://api-inference.huggingface.co/models/Qwen/Qwen2.5-Coder-32B-Instruct/v1/chat/completions (Request ID: BBblp7)
```
- Test get_hfapi_message_no_tool only if RUN_ALL
=> Fix 429 Client Error: Too Many Requests in CI test

docs/source/en/reference/agents.md, docs/source/hi/reference/agents.md, docs/source/zh/reference/agents.md, src/smolagents/agents.py
Create `PromptTemplates` typed dict.
=> Create PromptTemplates typed dict

examples/open_deep_research/README.md, examples/open_deep_research/run.py
Make question arg required in Open DeepResearch example.
```
$ python run.py -h
usage: run.py [-h] [--model-id MODEL_ID] [--api-base API_BASE] question
positional arguments:
question             for example: 'How many studio albums did Mercedes Sosa release before 2007?'
options:
-h, --help           show this help message and exit
--model-id MODEL_ID
--api-base API_BASE
```
=> Make question arg required in Open DeepResearch example

examples/open_deep_research/run.py, examples/open_deep_research/run_gaia.py
Remove unused api-base arg from Open DeepResearch example.
Note that the `api-base` arg is never used.
=> Remove unused api-base arg from Open DeepResearch example

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
This adds support for executing code that leverages non-standard comparison operators, such as in `pypika`
I came across this when trying to write a CodeAgent that could write SQL, but I wanted control over the query before it was sent to the DB.  `pypika` allowed me to add my own where clauses to every query prior to processing and will likely allow for more close auditing of the types of queries that the agent generates.
I'm very open to feedback for different ways of implementing this, but my primary issue was the following error from within the local_python_executor:
```unsupported operand type(s) for &: 'bool' and 'BasicCriterion'```
=> Add support for non-bool comparison operators.

src/smolagents/local_python_executor.py
Hello,
here is a simple replacement of `math.po2` to built-in `pow` function, where the third argument can be used by an agent.
Please tell me if a unit test is needed or so, 
Closes #546
=> Change math.pow -> pow

src/smolagents/agents.py, src/smolagents/prompts/code_agent.yaml, src/smolagents/prompts/toolcalling_agent.yaml, tests/test_agents.py
Move plan user prompt to YAML and test text of plan prompts.
=> Move plan user prompt to YAML and test text of plan prompts

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Refactor the `_operations_count` state setting.
With this PR, the `_operations_count` parameter becomes handled integrally by `evaluate_ast`.
=> Refactor operations count state setting

src/smolagents/models.py
It seems that it is not a bad idea to decide on message flattening based on info from LiteLLM.
However, I was unable to find anything in its internals or Ollama API to make a decision about whether the model is a VLM or not. So, for now, I had to hardcode that for llava which for now is the only VLM :/
Tested CodeAgent with llava:
```py
from smolagents import LiteLLMModel, CodeAgent
from PIL import Image
model = LiteLLMModel(api_base="http://localhost:11434", model_id="ollama/llava", num_ctx=16384)
agent = CodeAgent(model=model, tools=[])
agent.run("What is in the provided image?", images=[Image.open("./tests/fixtures/000000039769.png")])
```
It does take a while to produce something, but it seems to work still:
Not ideal by any means, but ...
LiteLLM itself has utility functions to check …
=> LiteLLMModel - detect message flatenning based on model information

src/smolagents/models.py
Related to issue [#414](https://github.com/huggingface/smolagents/issues/414).
This PR adds a default value of 5000 tokens for `max_new_tokens` amd `max_tokens` to `TransformersModel.__call__` to avoid using the corresponding `transformers` default value (= 20 tokens) which is too low for agentic tasks.
Usage example:
Modify the last few lines of the [Text2SQL example](https://huggingface.co/docs/smolagents/examples/text_to_sql) to be
```
from smolagents import CodeAgent, TransformersModel
agent = CodeAgent(
tools=[sql_engine],
model=TransformersModel("meta-llama/Meta-Llama-3.1-8B-Instruct"),
max_steps=5
)
agent.run("Can you give me the name of the client who got the most expensive receipt?")
```
=> Adding default parameter for max_new_tokens in TransformersModel

tests/test_local_python_executor.py
=> Test evaluate_condition

docs/source/en/guided_tour.md, src/smolagents/gradio_ui.py
Fixes https://github.com/huggingface/smolagents/issues/489
Honestly, I would have set this to `False` by default. But not to break the public API preserved the default behaviour by settings it to `True`.
Obviously if you prefer we can keep the same interface:
```py
def launch(**kwargs):
demo.launch(**({"share": True, "debug": True} | kwargs))
```
But that is a bit excessive to me.
=> Allow Gradio share parameter passthrough

examples/open_deep_research/README.md
This PR addresses issue #635 and correctly builds smolagents from smolagents/examples/open_deep_research.
=> Fix issue #635. Corrected installation instructions for open_deep_research

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Fix evaluate_condition for non-bool result, as discussed in:
- #634
I think there are 2 bugs in `evaluate_condition`:
- The call to `.all()` method in: https://github.com/huggingface/smolagents/blob/b20da6a74781e41bb652699e7501f07509fddb56/src/smolagents/local_python_executor.py#L759
- This should be called explicitly (when pertinent) by the calling code
- A library may return a non-bool result that does not implement the `.all` method
- The early return in: https://github.com/huggingface/smolagents/blob/cfe599c54a81412ea334e1f9d1f17189772428ef/src/smolagents/local_python_executor.py#L750-L751
- Introduced by:
- #612
- Gives a wrong result for: `pd.Series([1, 2, 3]) == pd.Series([2, 2, 2]) == pd.Series([3, 3, 3])`
- It was returning: `pd.Series([False, True, False]`
- Instead of raising a …
=> Fix evaluate_condition for non-bool result

src/smolagents/models.py, tests/test_models.py
~~Fixes stop sequence removal from model output if there is white space after the stop sequence. Previously, not all stop sequence characters would have been removed.~~
It was possible that any stop sequence could be missed. For example if your stop sequence is `<end_code>` but the model vocab includes `>'`, the model could choose that token and then the stop sequence would be missed. This PR should address all those cases.
=> Fix for MLX Model when stop sequence is followed by any chars

src/smolagents/gradio_ui.py
A better test taken from monitoring.py because when using Ollama with MultiStepAgent for reasons I could not identify sometimes the value is still None as set in Model.__init__
=> Allow for last_input_token_count=None

src/smolagents/models.py, src/smolagents/tools.py, src/smolagents/utils.py, tests/test_tools.py
If a tool decorated with `@tool` contains a multiline comment:
```py
@tool
def ssh_execute_command_with_agent(host: str, port: int, username: str, command: str) -> str:
"""This tool connects to a specified SSH server using the SSH agent for authentication
and executes a given command on the server. It returns the output of the command
or any errors encountered during execution.
Args:
host: The hostname or IP address of the server.
port: The SSH port to connect to (default is 22).
username: The SSH username for authentication.
command: The command to execute on the server.
Returns:
A string containing the command's output or any errors encountered.
"""
```
It breaks `to_dict`. It produces something like this:
```py
from smolagents import Tool
from typing import Any, Optional
class …
```
=> fix tool code generation in case of multiline descriptions

src/smolagents/models.py, tests/test_models.py
When the model is given a tool, but ignores the instruction to make a tool call and just returns text, the "NoneType is not iterable" exception message isn't explicit.
The code will now reach the more useful exception for this scenario:
https://github.com/huggingface/smolagents/blob/a17f915f61931a7f0a85f097fc19e7eca8fed536/src/smolagents/agents.py#L706-L707
Personally I hit this a fair amount when using OpenAIServerModel with local models (e.g. 32B distilled deepseek in LM Studio)
I've added a very simple throwaway test of the fix.
**Out of scope**
* It seems to me like the logic should be part of constructing ChatMessage rather than a fixup that callers have to remember to do afterwards.
* Testing/improving the integrated behaviour that the correct exception is actually what the model …
=> Improve missing toolcall exception

.github/workflows/tests.yml, src/smolagents/gradio_ui.py, tests/test_gradio_ui.py
The original `upload_file` method in `GradioUI` has several issues:
- Using a list as a default parameter: This is unsafe because if the parameter is modified, it will affect the global state.
- The logic for file type detection is quite problematic: It uses the `mimetypes.guess_type` method, which internally matches file types based on file extensions. After determining the file type with `mimetypes.guess_typ`e, it uses a reverse dictionary constructed from `mimetypes.types_map` to match the file type back to a file extension. This is redundant and overcomplicated. Additionally, the original code introduces bugs because multiple different file extensions can correspond to the same file type. This unintentionally modifies the original file extension.
My submitted code improves these two …
=> refactor: simplify file type checking from MIME to extension

src/smolagents/agents.py
Remove non-existent `subfolder` arg in `MultiStepAgent.from_hub`.
Currently a TypeError is raised if the `subfolder` arg is passed:
> TypeError: snapshot_download() got an unexpected keyword argument 'subfolder'
```python
CodeAgent.from_hub(repo_id, trust_remote_code=True, subfolder="tools")
src/smolagents/agents.py:934: in from_hub
download_folder = Path(snapshot_download(repo_id=repo_id, **download_kwargs))
E       TypeError: snapshot_download() got an unexpected keyword argument 'subfolder'
venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py:114: TypeError
```
=> Remove non-existent subfolder arg in MultiStepAgent.from_hub

src/smolagents/monitoring.py
Change-Id: I751c96e2dac113303006d1636b7122150ca165e8
Adjust the Monitor class in src/smolagents/monitoring.py. Adjust the following code:
`console_outputs = f"[Step {len(self.step_durations)-1}: Duration {step_duration:.2f} seconds"`
Modify the step counter so that it can match the main title in each block, reducing confusion.
=> Align step numbers in monitoring logging

src/smolagents/agents.py, src/smolagents/tools.py
Remove deprecated `resume_download` arg in from_hub.
Note that the `resume_download` param was deprecated in huggingface-hub 0.23 (May 2, 2024): https://github.com/huggingface/huggingface_hub/releases/tag/v0.23.0
- passing the parameter is just ignored
=> Remove deprecated resume_download arg in from_hub

.github/workflows/build_documentation.yml
Pass `notebook_folder` to build notebook docs.
This argument is necessary if we want to automatically convert our documentation Guides to Notebooks.
Fix #647, fix #211, fix #113.
=> Pass notebook_folder to build notebook docs

CONTRIBUTING.md, README.md
This is where I looked at least. I've kept the existing text I've moved exactly the same.
=> Move contributing details into contributing file

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
It's a common practice to make constants module variables. This PR applies that to the `dangerous_patterns` variable in `import_modules`.
This has several advantage:
- Users opening this module understanding directly that there is a concept of dangerous patterns without needing to dive into the code
- `get_safe_module` requires one less parameters
- Users can now override it if they need it e.g.:
```
import smolagents.local_python_executor
local_python_executor.DANGEROUS_PATTERNS = tuple()
```
- This variable can also now be mocked for tests if required.
=> Make dangerous_patterns a module variable

pyproject.toml
Pin transformers < 4.49.0 to fix TypeError: LlavaProcessor: got multiple values for keyword argument 'images'.
Fix #692.
=> Pin transformers < 4.49.0 to fix TypeError: LlavaProcessor: got multiple values for keyword argument 'images'

tests/test_all_docs.py
Fix test docs: glob `.mdx` (instead of `.md`) doc files once that the file extensions have been renamed.
Issue introduced by:
- #691
CC: @accupham
=> Fix test docs

src/smolagents/tool_validation.py, tests/test_tool_validation.py, tests/test_tools.py
Fix `validate_tool_attributes` for non-literal defaults.
Currently, defining an `__init__` keyword argument that defaults to a variable (`arg=variable`) does not raise an error.
=> Fix validate_tool_attributes for non-literal defaults

src/smolagents/_function_type_hints_utils.py
This PR enhances the docstring parser to support Google-style docstrings that include parameter types (e.g., `x (float): ...`). The changes are backward-compatible and maintain support for docstrings without parameter types (e.g., `x: ...`).
- Updated the regular expression in the docstring parser to handle parameter types.
The parser now correctly handles docstrings with parameter types:
```python
def multiply(x, y):
"""
Args:
x (float): The first number to multiply.
y (float): The second number to multiply.
"""
return x * y
```
Previous the args may be reconized as "x (float)" and raise the exception "Cannot generate JSON schema for multiply because the docstring has no description for the argument 'x'".The changes reduces the need for users to manually adjust their docstrings.
=> Ignore parameter types in tool docstrings

src/smolagents/tools.py
Remove article section from `launch_gradio_demo` Interface.
Currently, the tool description appear both, above and below the input components.
This PR removes the description appearing below the input components, called `article` attribute in the Gradio Interface.
=> Remove article section from launch_gradio_demo Interface

tests/test_search.py
Fix CI test error: DuckDuckGoSearchException: 202 Ratelimit.
Skip `DuckDuckGoSearchTool` test_exact_match_arg if not RUN_ALL.
Fix #738.
=> Fix CI test error: DuckDuckGoSearchException: 202 Ratelimit

docs/source/en/examples/multiagents.mdx
Rename managed agent in multiagents docs to avoid confusing the LLM.
Sometimes, the LLM confuses the agent name with the `DuckDuckGoSearchTool` name (web_search) and calls it with `query` arg instead of `task`arg.
=> Rename managed agent in multiagents docs to avoid confusing the LLM

examples/open_deep_research/requirements.txt
Add audioop-lts as Python >=3.13 Open DeepResearch requirement to use pydub.
Related to discussion in:
- #746
=> Add audioop-lts as Python>=3.13 Open DeepResearch requirement for pydub

src/smolagents/cli.py
This PR fixes `LiteLLMModel` API key handling in the CLI. Before this, when running without `--api-key`, the CLI defaulted to using `OPENAI_API_KEY` even for non-OpenAI models, preventing LiteLLM's built-in API key detection based on the model provider.
I've tested the fix with:
```bash
export OPENAI_API_KEY="sk-openai-key"
export ANTHROPIC_API_KEY="sk-anthropic-key"
smolagent "What is the 42nd decimal digit of π?" --model-type "LiteLLMModel" --model-id "anthropic/claude-3-7-sonnet-latest"
```
Since the `load_model` function is called in both `smolagent` and `webagent`, this fix should improve this behavior for both.
Closes #787
=> Fix LiteLLMModel API key usage in CLI

examples/open_deep_research/README.md
Update Open DeepResearch to install smolagents from local path in editable mode.
In order to be sure that the running of Open DeepResearch is aligned with the smolagents version, smolagents should be installed from the local path in editable mode.
Related to:
- #777
=> Update Open DeepResearch to install smolagents from local path

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Support importing scipy and sklearn.
Currently, an AttributeError is raised: `AttributeError: module 'scipy.sparse._coo' has no attribute 'upcast'`
```python
src/smolagents/local_python_executor.py:1314: in evaluate_ast
return import_modules(expression, state, authorized_imports)
src/smolagents/local_python_executor.py:1077: in import_modules
state[alias.asname or alias.name] = get_safe_module(raw_module, authorized_imports)
src/smolagents/local_python_executor.py:1053: in get_safe_module
attr_value = get_safe_module(attr_value, authorized_imports, visited=visited)
src/smolagents/local_python_executor.py:1053: in get_safe_module
attr_value = get_safe_module(attr_value, authorized_imports, visited=visited)
src/smolagents/local_python_executor.py:1053: in get_safe_module
attr_value = …
```
=> Support importing scipy and sklearn without AttributeError: module 'scipy.sparse._coo' has no attribute 'upcast'

src/smolagents/agents.py, tests/test_agents.py
Fix and test `_validate_tools_and_managed_agents`.
Revert PR:
- #721
Fix #795.
=> Fix and test validate_tools_and_managed_agents

examples/open_deep_research/scripts/visual_qa.py
Improve dependency loading of Open DeepResearch visual_qa.
Before this PR:
- the processor for "HuggingFaceM4/idefics2-8b-chatty" model was loaded by default, even if not used in run.py
- this required HF_TOKEN to be defined as environment variable, even if not used in run.py
Related to:
- #807
=> Improve dependency loading of Open DeepResearch visual_qa

examples/open_deep_research/run.py, examples/open_deep_research/run_gaia.py
Support other models than o1 in Open Deep Research:
- Use `reasoning_effort` only with o1 model
Related to:
- #760
- #676
=> Support other models than o1 in Open Deep Research

tests/test_remote_executors.py
Fix and refactor tests of Docker executors.
There were multiple errors raised by the tests of Docker executors:
- `TypeError: DockerExecutor.__init__() got an unexpected keyword argument 'tools'`
- `TypeError: DockerExecutor.__init__() got an unexpected keyword argument 'initial_state'`
- `TypeError: Logger.log() missing 1 required positional argument: 'msg'`
- `RuntimeError: Failed to initialize Jupyter kernel: 500 Server Error for http+docker://localhost/v1.48/containers/3c46306598f69647c6c3d40e3ef17b044ae7b47ea3876f3cde41aed07eaaf3a1/start: Internal Server Error ("driver failed programming external connectivity on endpoint interesting_herschel (e46e013e2f4f571693b7833124b806da357617cfc32c40904aa54cd2cc0d907a): Bind for 127.0.0.1:8888 failed: port is already allocated")`
- because …
=> Fix and refactor tests of Docker executors

src/smolagents/default_tools.py
super().__init__(**self**) instead of **super().__init__()**. I removed the **self**, which was causing the following issue when using it: 
```python
TypeError: GoogleSearchTool.__init__() got an unexpected keyword argument 'provider'
```
in the following code: 
```python
model = HfApiModel(
"Qwen/Qwen2.5-Coder-32B-Instruct", provider="together", max_tokens=8096
)
web_agent = CodeAgent(
model=model,
tools=[
GoogleSearchTool(provider="serpapi"),
VisitWebpageTool(),
calculate_cargo_travel_time,
],
name="web_agent",
description="Browses the web to find information",
verbosity_level=0,
max_steps=10,
)
```
from the [multiagent_notebook](https://colab.research.google.com/github/huggingface/agents-course/blob/main/notebooks/unit2/smolagents/multiagent_notebook.ipynb) of the agents course, unit …
=> Remove unnecessary self argument in GoogleSearchTool super() call

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Fix call from dict with `LocalPythonExecutor`.
Currently, the code
```python
d = {'func': lambda x: x + 10}
d['func'](1)
```
raises `InterpreterError: Cannot subscript object of type dict`.
=> Fix call from dict with LocalPythonExecutor

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Make local Python interpreter safer by checking if returns builtins.
=> Make local Python interpreter safer by checking if returns builtins

docs/README.md
This PR fixes #249. Please feel free to let me know what do you think. Thanks.
@albertvillanova
=> Fix translation guide as it points to invalid location

src/smolagents/memory.py, tests/test_memory.py
Fix message for observations without tool_calls.
Supersede:
- #571 
Related to:
- #836
=> Fix message for observations without tool_calls

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Make local Python interpreter safer by adding builtins to dangerous modules:
- treat builtins as the rest of dangerous modules
- do not raise error if explicitly allowed
- add tests
=> Make local Python interpreter safer by adding builtins to dangerous modules

src/smolagents/vision_web_browser.py
Fix CLI webagent:
> TypeError: LocalPythonExecutor.__call__() takes 2 positional arguments but 3 were given
It was broken after the merge of:
- #733
=> Fix CLI webagent

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Skip dangerous modules instead of dangerous patterns.
After this PR:
- we support the inoffensive import of `pandas.io`
- we no longer (info) log the skipping of dangerous attributes
EDIT:
- We have also added an extra security check for dangerous functions
Fix #663.
Supersede and close #664.
=> Check dangerous modules instead of dangerous patterns

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Improve `evaluate_subscript`:
- Support pandas operators `.at` and `.iat`
- Support custom class with `__getitem__` but without `__contains__`
- Simplify the code
- Test all cases
Currently:
- custom class with `__getitem__` but without `__contains__` might get into an infinite loop: check test in d7332218023239a9f80679f762c9
- pandas operators `.at` and `.iat` are not supported:
```
FAILED tests/test_local_python_executor.py::test_evaluate_subscript[ser.at[1]-state36-3] - KeyError: 0
FAILED tests/test_local_python_executor.py::test_evaluate_subscript[df.at[1, 'y']-state49-4] - TypeError: DataFrame._get_value() missing 1 required positional argument: 'col'
FAILED tests/test_local_python_executor.py::test_evaluate_subscript[df.at[5, 'y']-state50-3] - TypeError: DataFrame._get_value() …
```
=> Improve evaluate_subscript

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Test all dangerous functions and fix check of dangerous function `os.system`:
- test all dangerous functions, so we avoid issues like:
- #909
- fix check of dangerous function `os.system`:
- this issue was found thanks to the test above
- the module name of this function is `posix` instead of `os`
```python
In [1]: import os
In [2]: os.system.__module__
Out[2]: 'posix'
```
=> Test all dangerous functions and fix check of os.system

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Test vulnerability for dangerous modules: improve test coverage
EDIT: See https://github.com/huggingface/smolagents/pull/929#pullrequestreview-2672044981
~~Add more dangerous modules to security check:~~
- ~~code~~
- ~~codecs~~
- ~~distutils~~
- ~~glob~~
- ~~pickle~~
- ~~posix: see #911~~
- ~~shelve~~
- ~~sqlite3~~
- ~~venv~~
=> Test vulnerability for dangerous modules

README.md
Fixes #932. Updated the broken link to the benchmarking code in the README to point to the correct location.
=> Fix broken link to benchmarking code in README

src/smolagents/gradio_ui.py
Fixes this issue:
```
Traceback (most recent call last):
File "/Users/user/Documents/Dev/sysradium/ml-playground/agents/smol_example.py", line 163, in <module>
demo = GradioUI(agent).create_app()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/user/Documents/Dev/sysradium/ml-playground/.venv/lib/python3.12/site-packages/smolagents/gradio_ui.py", line 270, in create_app
f"# {self.name.replace('_', ' ').capitalize() or 'Agent interface'}"
```
Name is optional and thus by default is `None`:
https://github.com/huggingface/smolagents/blob/af03d17813c987fbb79e303fadf4713b29ccf2f1/src/smolagents/agents.py#L214
Also if name is not event specified it is `None` as well:
https://github.com/huggingface/smolagents/blob/main/src/smolagents/gradio_ui.py#L187
Hence the bugfix. 
Maybe we can consider using this …
=> Fix Gradio UI for unnamed agents

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
I would like to add a counter class so the operation counter value will not be desynchronized when agents create functions. 
Closes #871
=> Introduce counter class

src/smolagents/models.py, tests/test_models.py
Fix `AzureOpenAIServerModel` to not call `openai.OpenAI`.
Note that before this PR:
- `AzureOpenAIServerModel` calls `super().__init__`
- `OpenAIServerModel` instantiates `openai.OpenAI`, which is not required
- Then, `AzureOpenAIServerModel` instantiates `openai.AzureOpenAI`, the only required client
This PR fixes `AzureOpenAIServerModel` so it does not call `openai.OpenAI`, reducing latency.
=> Fix AzureOpenAIServerModel to not call openai.OpenAI

src/smolagents/cli.py, src/smolagents/models.py, tests/test_models.py
Support passing `flatten_messages_as_text` to `OpenAIServerModel` and test `flatten_messages_as_text` for all models.
See discussion in: https://github.com/huggingface/smolagents/issues/944#issuecomment-2717695966
=> Support passing flatten_messages_as_text to OpenAIServerModel and test

src/smolagents/tools.py, src/smolagents/utils.py, tests/test_agents.py, tests/test_tool_validation.py, tests/test_utils.py
Fix tool function implementation.
Currently, no `@tool` decorated function can be used in remote code execution, because:
- `RemotePythonExecutor.send_tools`
- calls `get_tools_definition_code`
- calls `validate_tool_attributes`
Currently, when using `@tool` decorator, `validate_tool_attribute` raises an error because the dynamically created `SimpleTool` class has required parameters in `__init__` without default values:
https://github.com/huggingface/smolagents/blob/812c2d2e798701024d0259e3d46ab4f45a228185/src/smolagents/tools.py#L839-L853
```python
ValueError: Tool validation failed for SimpleTool:
Parameters in __init__ must have default values, found required parameters: output_type, inputs, name, function, description
```
This PR:
- For tool functions, dynamically create the …
=> Fix tool function implementation

docs/source/en/tutorials/tools.mdx
The example of how to integrate smolagents with an MCP server was broken. This fixes it. Should resolve https://github.com/huggingface/smolagents/issues/442
=> Fix broken example of using MCP Server

src/smolagents/remote_executors.py, tests/test_remote_executors.py
Support passing any kwargs to E2BExecutor Sandbox.
Supersede and close #550.
=> Support passing any kwargs to E2BExecutor Sandbox

src/smolagents/models.py, tests/test_models.py
The official code doesn't work, self.client will be always set to None.
=> Fix OpenAIServerModel client

docs/source/en/guided_tour.mdx, docs/source/en/tutorials/secure_code_execution.mdx, src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Forbid all modules by default except whitelist `authorized_imports`.
This PR implements a more robust security approach: use a deny-by-default policy and only whitelist specific modules that are known to be safe for your use case, rather than trying to maintain a comprehensive blacklist
As discussed in: https://github.com/huggingface/smolagents/pull/929#pullrequestreview-2672044981
=> Forbid all modules by default except whitelist authorized_imports

src/smolagents/agents.py, tests/test_agents.py, tests/test_monitoring.py
Until now we log all errors to agent memory, display them as a summary version (not the whole traceback) and keep running the agent. But although this makes sense for AgentParsingError and AgentExecutionError, it does not for AgentGenerationError which should never happen and retry. If the LLM call fails, it's an implementation issue, not an error from the agent, so this should just interrupt the agent run and log the full traceback!
=> Raise agent generation errors

src/smolagents/agents.py, tests/conftest.py, tests/fixtures/agents.py, tests/test_agents.py
Fix Agent.from_hub for agents exported in previous `smolagents` versions.
Currently they raise:
> KeyError: 'executor_type'
The functionality to share agents to the Hub was introduced in smolagents-1.9.0:
- #533
However, agents exported with smolagents-1.9.0 are no longer importable with smolagents-1.10.0 after:
- #645
- #733 
This PR allows importing agents exported either with v1.9 or v1.10.
Fix #978.
=> Fix Agent.from_hub for older smolagents exports

src/smolagents/models.py
@aymeric-roucher 
Fixes a regression introduced here: https://github.com/huggingface/smolagents/commit/e432d4190d36296456b62f358359be3bc184be34#diff-0319e64c7d0f9e302a7c7a0dd60f04dedb7d4dcf7dbe9e046543335654a9efa1R252
ID must be a string, since later on it is being added to a chat message that a json parser will fail to parse.
=> Regression fix: ChatMessageToolCall id must be a string

src/smolagents/agents.py, tests/fixtures/agents.py, tests/test_agents.py
Fix prompt templates in Agent.from_hub.
Currently, custom `prompt_templates` are exported but ignored when importing and the default ones are used instead.
=> Fix custom prompt templates in Agent.from_hub

src/smolagents/default_tools.py, src/smolagents/models.py, tests/test_agents.py
Sometimes APIs return proper tool calls, but as a JSON string instead of a dictionary: this was not parsed as json using `parse_json_if_needed`, thus the usage of said args would fail.
This PR fixes it and adds a regression test.
Here is now how the API models returns are processed after this PR
```
if return has a built in tool call:
if this tool call has incompletly parsed arguments like a string '{"location": "Paris"}' instead of the dict '{"location": "Paris"}' , parse them
if return has no built-in tool call:
try parsing the tool call from the return string
if no tool call is found, fail
```
=> Always parse arguments from API tool calls

src/smolagents/prompts/toolcalling_agent.yaml
This PR corrects a double space in the ToolAgent system prompt
=> Fix double space in toolcalling_agent.yaml

src/smolagents/agents.py, src/smolagents/memory.py
=> Update images type and docstring

src/smolagents/utils.py, tests/test_models.py
Support JSON string arguments in tool calls.
This PR adds support for handling tool call arguments that are provided as a JSON string. When a tool call's arguments are passed as a JSON-encoded string rather than a direct JSON object, the function now properly parses this string into a Python object.
For example, arguments can now be passed in these two formats:
- As a direct JSON object: `"arguments": {"city": "New York"}`
- As a JSON string: `"arguments": "{\\"city\\": \\"New York\\"}"`
Both formats will result in proper Python objects in the tool call result.
Fix `parse_json_blob`.
See discussion in: https://github.com/huggingface/smolagents/pull/1000#discussion_r1998082112
=> Support JSON string arguments in tool calls

src/smolagents/models.py, tests/test_models.py
Pass `trust_remote_code` to transformers tokenizer/processor.
=> Pass trust_remote_code to transformers tokenizer/processor

examples/open_deep_research/scripts/visual_qa.py, src/smolagents/_function_type_hints_utils.py, src/smolagents/agent_types.py, src/smolagents/remote_executors.py, src/smolagents/tools.py, src/smolagents/utils.py, src/smolagents/vision_web_browser.py, tests/test_agents.py, tests/test_final_answer.py, tests/test_models.py, tests/test_remote_executors.py, tests/test_tools.py, tests/test_types.py
Fix code using pillow required dependency.
Note that `pillow` is a required dependency since:
- [More robust log step class, and new examples](https://github.com/huggingface/smolagents/commit/a830b1721affb59858cf59d05e54e6859d325b3b#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)
This PR removes the unnecessary functions:
- `_is_pillow_available()`
- `transformers.is_vision_available()`
Additionally, this PR fixes some type hints that used `PIL.Image` (module) instead of `PIL.Image.Image` (class).
=> Fix code using pillow required dependency

tests/test_agents.py, tests/test_tools.py, tests/test_utils.py
Fix tests of Agent.save and Tool.save.
Currently, when running the tests, they generate 2 directories in the current working directory: `agent_export` and `output`.
This PR fixes the tests so they save the Agent/Tool in a test-specific temporary directory.
=> Fix tests of Agent.save and Tool.save

src/smolagents/agents.py, tests/test_agents.py
Recently, I noticed that some models (such as claude-sonnet-3.7) generate imaginary tool calls in the CodeAct agent. Please take a look at the screenshot below; there is a "Calling tools" section right after the code. It is also how the tool calls are stored in history. Since there is no <end_code> token in the history, models are instructed in a few-shot way not to generate <end_code> token but to generate these imaginary tool calls instead.
These calls do not actually break anything, but they are a colossal waste of tokens.
Fixes this issue: #375 
The simplest solution is to add <end_code> in history, and this PR does exactly that. This trains a model to generate it instead of imaginary tool calls.
=> Bugfix: adding <end_code> to prevent imaginary tool calls in CodeAgent

src/smolagents/gradio_ui.py
Closes https://github.com/huggingface/smolagents/issues/789
This will allow the use of gradio hot reload feature. For example:
```py
model = ...
agent = CodeAgent(
tools=[
ocr_document,
ssh_execute_command_with_agent,
generate_temp_file,
download_file,
],
model=model,
)
demo = GradioUI(agent).create_app()
if __name__ == "__main__":
demo.launch(debug=True, share=False)
```
When launched with:
```
gradio example.py 
```
Will enable gradio hot reload. I.e. any changes to `example.py` will reload the file and restart a server.
=> allow users to retrieve original Gradio app

src/smolagents/agents.py, src/smolagents/tools.py
Set Agent/Tool requirements as a sorted list.
Note that currently, tools requirements returned by `to_dict` are a set.
=> Set Agent/Tool requirements as a sorted list

pyproject.toml, src/smolagents/agent_types.py
Make pandas a test extra dependency only.
Note that it is not a required dependency because we don't use it in the base code. We want to be sure to support it, so we only use it in tests.
Fix #1080.
=> Make pandas a test extra dependency only

src/smolagents/_function_type_hints_utils.py, tests/test_function_type_hints_utils.py
Fix `get_json_schema` for docstrings with type annotations.
Note that this was already addressed by:
- #724
However, that PR introduced a bug when parsing multiple arguments: the docstring with
```
Args:
x (int): An integer parameter with type in docstring.
y (float): A float parameter with type in docstring.
```
was wrongly parsed into (y parameter was included in x description):
```python
{'x': 'An integer parameter with type in docstring. y (float): A float parameter with type in docstring.'}
```
This PR fixes that issue.
Additionally, this PR fixes the return description when the docstring contains the return type. Before, the docstring
```
Returns:
float: The calculated result.
```
was wrongly parsed (including the return type into the return description):
```python …
```
=> Fix get_json_schema for docstrings with type annotations

docs/source/en/tutorials/tools.mdx, docs/source/hi/tutorials/tools.mdx, src/smolagents/tools.py, tests/test_tools.py
Add `trust_remote_code` to `ToolCollection.from_mcp`.
**Important:** This is a *breaking change*:  
- Existing code that does not pass `trust_remote_code` will now raise an error.  
- However, this change is necessary for security reasons: helps users be more aware of the risks associated with executing remote code
Related to:
- #1085 
- #1090
=> Add trust_remote_code to ToolCollection.from_mcp

docs/source/en/guided_tour.mdx, docs/source/en/tutorials/secure_code_execution.mdx, src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
@albertvillanova this PR re-adds authorization for submodules whose top module was allowed, like authorizing access to `numpy.random` if `numpy` was authorized. We need to be careful to avoid this potentially allowing harmful submodules of authorized modules, but `tests/test_local_python_executor.py::TestLocalPythonExecutorSecurity::test_vulnerability_via_submodules` should catch this vulnearbility?
=> Re-authorize submodule imports if top was allowed

src/smolagents/tools.py
Previously, a bad version of forward() in a tool would report an exception like:
```
Exception: In tool 'user_input', 'forward' method should take 'self' as its first argument, then its next arguments should match the keys of tool attribute 'inputs'.
```
Now, I've explicitly included the expected and actual parameters. I also hope this made the code clearer.
```
Exception: In tool 'user_input', 'forward' method parameters were {'prompt'}, but expected {'question'}. It should take 'self' as its first argument, then its next arguments should match the keys of tool attribute 'inputs'.
```
The code passes `make test` and `make quality` fwiw.
Thanks!
/charles
```
make quality
ruff check examples src tests utils
All checks passed!
ruff format --check examples src tests utils
63 files already …
```
=> Change: expanded error exception for incorrect tool parameters

examples/gradio_ui.py, src/smolagents/agents.py, src/smolagents/gradio_ui.py, tests/test_monitoring.py
This PR adds a specific field in gradio ChatMessages to display possible `observations_images`: very useful for instance when running VLM-based browser agents, with a callback at the end of each step to log screenshots!
=> Gradio UI: log observations images

examples/agent_from_any_llm.py, src/smolagents/agents.py, tests/test_agents.py
`AgentGenerationErrors` are designed to be caught, because they mean that inference was improperly setup: however for `ToolCallingAgent` where sometimes the model can just output bad formatted tool calls **_on the api side_** that do not get extracted as a proper tool call, we can be more indulgent and let the model retry by making the error an `AgentParsingError` instead, which is not raised but returned to the agent. This is mostly a hotfix, to be refined later. Also, reminder: `ToolCallingAgent` is not the primary class that we support, the preferred class is `CodeAgent`.
=> Replace AgentGenerationError with AgentParsingError for ToolCallingAgent

src/smolagents/agents.py
**Bug Description**
When planning_interval=1 was set in MultiStepAgent, the agent would never execute planning steps. This was counter-intuitive, as users would expect planning to occur at every step with this setting.
This can be reproduced by using the example `agent_from_any_llm.py` with:
`agent = CodeAgent(tools=[get_weather], model=model, verbosity_level=2, planning_interval=1)
print("CodeAgent:", agent.run("What's the weather like in Paris? Once you have found out the current temperature, divide it by 2.345 and return the result as a string. Make sure to use Python code to do this. Then, as a third step, write a story about a cat that is a wizard and can fly and somehow use the calculated number in that story."))`
**Root Cause**
The issue was in the condition used to determine when …
=> Fix planning_interval=1 bug in MultiStepAgent

pyproject.toml
Unpin pillow < 11.2.0.
As explained in the closing issue #1138:
- pillow 11.2.0 version was yanked: https://pypi.org/project/pillow/11.2.0/
- https://github.com/python-pillow/Pillow/issues/8722#issuecomment-2771577726
- the root issue was reported to pillow:
- https://github.com/python-pillow/Pillow/issues/8857
- and fixed:
- https://github.com/python-pillow/Pillow/pull/8859
Fix #1138.
=> Unpin pillow < 11.2.0

src/smolagents/models.py
fix #1136
This support is already present in another model client such as `HfApiModel` and `OpenAIServerModel`.
I've tested it with the following code:
```python
from smolagents import CodeAgent, DuckDuckGoSearchTool, VLLMModel
search_tool = DuckDuckGoSearchTool()
model_name = "google/gemma-3-4b-it"
model = VLLMModel(model_id=model_name, client_kwargs={"max_model_len": 65536}) # new functionality!
agent = CodeAgent(tools=[search_tool], model=model)
result = agent.run("How did Real Madrid do in their last La Liga match?")
result
```
BTW, there are currently no tests for `VLLMModel` in `test_models.py` and it's not described in the guided tour docs.
=> Pass vLLM (VLLMModel) model client params as `client_kwargs`

src/smolagents/_function_type_hints_utils.py, tests/test_function_type_hints_utils.py
Fix `get_json_schema` for keyword in description.
Supersede:
- #1094
=> Fix get_json_schema for keyword in description

src/smolagents/memory.py
I encountered the same issue described in #1139 and have identified user message in PlanningStep as the cause. After testing it directly in Azure's playground, I was able to reproduce the error. The new message resolves the problem for me.
=> Fix: adjust PlanningStep user message to avoid azure's content filter

src/smolagents/agents.py
`provide_final_answer()` has an optional argument `images`, but since no default value is provided, this can raise exceptions if you don't specify it. Simply defaulting to `None` should give the desired functionality.
=> Fix: Add default value to optional argument

docs/source/en/tutorials/memory.mdx
Clarify tool usage in agent step tutorial.
I would consider this as a hotfix needed to have the docs aligned with the code implementation. However, I think we should simplify the procedure.
Fix #1170.
Also related to:
- #1165
=> Clarify tool usage in agent step tutorial

src/smolagents/tool_validation.py, src/smolagents/tools.py, tests/test_tool_validation.py
Fix tool validation with multiple assignments.
Currently, a tool with these code lines
```python
a, b = "1", "2"
c = a + b
```
raises an error:
```python
[
"Name 'a' is undefined.",
"Name 'b' is undefined.",
]
```
=> Fix tool validation with multiple assignments

src/smolagents/remote_executors.py
This PR enhances the `DockerExecutor` class by adding the ability to specify custom Docker image names, control the image building process, and configure container runtime parameters. Previously, the executor would always build a new image with a hardcoded name ("jupyter-kernel") on initialization and had limited container configuration options.
- Added new parameters to `DockerExecutor.__init__`:
- `image_name`: Allows specifying a custom Docker image name (default: "jupyter-kernel")
- `rebuild_image`: Controls whether to rebuild the image even if it exists (default: True)
- `container_run_kwargs`: Enables passing additional keyword arguments to the Docker container run command
- Implemented image existence checking logic:
- If `rebuild_image` is False, the executor will check if the …
=> feat: add custom Docker image support and enhanced configuration for DockerExecutor

src/smolagents/_function_type_hints_utils.py, tests/test_tools.py
Allows defining enum choices with `@tool` using native [`Literal` type annotations](https://typing.python.org/en/latest/spec/literal.html#literal) instead of via docstring.
Closes https://github.com/huggingface/smolagents/issues/1194.
This is my first contribution, so let me know if there is anything I can improve, thank you! 🙂 
- ✅ `make quality` passes
- ✅ `make tests` passes
- ✅ New tests added for the functionality
=> Support `Literal` type annotations in `@tool` for defining enums

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Support class docstrings in LocalPythonExecutor.
Fix #1189.
=> Support class docstrings in LocalPythonExecutor

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Support annotated assignment in LocalPythonExecutor.
Fix #1189 second issue.
=> Support annotated assignment in LocalPythonExecutor

src/smolagents/agents.py, tests/test_agents.py
I suggest to mark `MultiStepAgent` as an abstract class since it is not meant to be instantiate on its own.
Also it has 2 methods, that other agent implementation must implement.
Before, when I just started using this library I shoot myself in a foot but instantiating `MultiStepAgent` and then trying to figure out why it quickly goes through `max_steps` and halts.
=> Make MultiStepAgent and abstract class

src/smolagents/tools.py, tests/test_tools.py
This PR addresses the bug where calling tool(a_function) was editing the function signature of the the function that was passed in. Instead of this, the function should be wrapped so that the smolagents code doesn't affect the function that was provided.
=> fix: creating tool should not affect function that is being wrapped

tests/test_models.py
Fix CI test by updating LiteLLM error message.
This fix is required after `litellm-1.66.2` release: https://pypi.org/project/litellm/1.66.2/
See: https://github.com/huggingface/smolagents/actions/runs/14510658163/job/40708376431?pr=1211
```
FAILED tests/test_models.py::TestLiteLLMModel::test_call_different_providers_without_key[groq/llama-3.3-70b-Missing API Key] - assert 'Missing API Key' in '<ExceptionInfo litellm.BadRequestError: GroqException - {"error":{"message":"Invalid API Key","type":"invalid_request_error","code":"invalid_api_key"}}\n tblen=7>'
+  where '<ExceptionInfo litellm.BadRequestError: GroqException - {"error":{"message":"Invalid API Key","type":"invalid_request_error","code":"invalid_api_key"}}\n tblen=7>' = str(<ExceptionInfo litellm.BadRequestError: GroqException - …
```
=> Fix CI test by updating LiteLLM error message

src/smolagents/local_python_executor.py
The `custom_tools` parameter's docstring of `evaluate_ast()` erroneously referred to `static_tools` here: 
```
custom_tools (`Dict[str, Callable]`):
Functions that may be called during the evaluation. These static_tools can be overwritten.
```
=> Fix typo in evaluate_ast() docs: static_tools -> custom_tools

.github/workflows/tests.yml, docs/source/en/reference/tools.mdx, docs/source/en/tutorials/tools.mdx, src/smolagents/__init__.py, src/smolagents/mcp_client.py, tests/test_mcp_client.py
Fixes #1179
As discussed in the issue above the idea is to introduce a new class: `MCPClient` allowing our users to manage the connection with one or several MCP servers.
It supports 2 syntaxes:
1. with a context manager for a fully managed connection with the MCP server, similar to what `ToolCollection.from_mcp` is doing today.
2. a new try / finally syntax which allow more fine grained control over the connection and its lifecycle via a new mcp_client instance.
Note 1: I have moved the `.connect()` inside the __init__ of the MCPClient I am not sure it is desirable here. Initially I kept it outside even though it's one more call in my opinion it makes things more explicit while if you want less boilerplate you can always use the with syntax.
Note 2: I have added a couple of tests but …
=> SmolAgents MCP Client

examples/rag.py
The doc description incorrectly states that BM25 retriever leads to semantic search. This corrects it so it is more precise.
=> Change language from semantic to lexical for BM25

src/smolagents/__init__.py, src/smolagents/mcp_client.py
The readme instructions added in https://github.com/huggingface/smolagents/pull/1200 
say to import MCPClient like
```
from smolagents import MCPClient, CodeAgent
```
This PR is to add MCPClient to the `__init__` so that the code in the readme is accurate
=> Move MCPClient to root-level lib and manage optional dependencies

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Set `__name__` to `"__main__"` in local Python interpreter.
Fix #1229.
=> Set __name__ to "__main__" in local Python interpreter

examples/open_deep_research/requirements.txt
Update Open DeepResearch requirements: only `google-search-results` is required.
Note that depending on the installation order, `serpapi` and `google-search-results` will overwrite each other.
As discussed with @A-Mahla.
Related to:
- #1054
- CC: @edlee123
=> Update Open DeepResearch requirements

pyproject.toml
Lower Pillow dependency minimum version to 10.0.1:
- 10.0.1 addressed the security vulnerability CVE-2023-4863
The library doesn't use any Pillow 11‑only APIs; this change improves compatibility with older packages.
Additionally, lower versions are built in pyodide, which is used by the Wasm executor:
- #1261
=> Lower Pillow dependency minimum version to 10.0.1

src/smolagents/remote_executors.py, tests/test_remote_executors.py
Fix remote executor send_tools to skip pip install on empty package list.
We were getting an error log:
```
ERROR: You must give at least one requirement to install (see "pip help install")
```
Now we first check if there are new requirements before running `pip install`:
```python
f"!pip install {' '.join(packages_to_install)}\n"
```
=> Fix remote executor send_tools to skip pip install on empty package list

src/smolagents/remote_executors.py
Remove smolagents installation from remote executors.
This PR stops forcing the core smolagents package to be installed in remote environments, resulting in fasting code executions.
=> Remove smolagents installation from remote executors

pyproject.toml
Hotfix CI: pin mcp < 1.7.0.
Close #1284.
=> Hotfix CI: pin mcp < 1.7.0

README.md, docs/source/en/examples/multiagents.mdx, docs/source/en/guided_tour.mdx, docs/source/en/tutorials/inspect_runs.mdx, examples/open_deep_research/visual_vs_text_browser.ipynb, pyproject.toml
Remove `duckduckgo-search` as required dependency.
This PR decouples the DuckDuckGo search tool from the core package.
- Reduce the install footprint for users who don't need the web search tool or prefer an alternative
- Keep core package lean and focused
Additionally, note that `duckduckgo-search` depends on `lxml`, that is not a pure-Python package. This is problematic for the Wasm executor:
- #1261
=> Remove duckduckgo-search as required dependency

src/smolagents/remote_executors.py
Refactor `RemotePythonExecutor.send_tools` to delegate package installation to `install_packages`.
This PR refactors the `RemotePythonExecutor.send_tools` method to improve code clarity and separation of concerns by delegating package installation logic to the existing `install_packages` method. This change avoids duplication and centralizes package management behavior in a single location, making the codebase easier to maintain and extend. Note that after this change `run_code_raise_errors` is called twice instead of one time.
This refactor also improves extensibility by ensuring that subclasses overriding the `install_packages` method can customize package installation behavior when `send_tools` is called. See:
- #1261
=> Refactor RemotePythonExecutor.send_tools to call install_packages

src/smolagents/remote_executors.py
Remove unnecessary dependencies from DockerExecutor image.
This PR updates the DockerExecutor's embedded Dockerfile to only install the packages required for the Jupyter Kernel Gateway. 
Unused dependencies like `numpy`, `pandas`, and the `notebook` UI have been removed to reduce image size and build time:
- Smaller Docker image footprint
- Faster build times
Tests: I have locally tested TestDockerExecutor with `RUN_ALL=1`.
=> Remove unnecessary dependencies from DockerExecutor image

pyproject.toml
Unpin mcp < 1.7.0, once the issue has been fixed on their side:
- https://github.com/modelcontextprotocol/python-sdk/pull/619
They have made a patch release: 1.7.1
- https://github.com/modelcontextprotocol/python-sdk/releases/tag/v1.7.1
- https://pypi.org/project/mcp/1.7.1/
Close #1287.
=> Unpin mcp < 1.7.0

docs/source/en/guided_tour.mdx, docs/source/en/tutorials/tools.mdx
Quick typo fix: `you` --> `your`
=> docs: fix typo

docs/source/en/examples/multiagents.mdx, pyproject.toml
Remove `markdownify` as required dependency.
This PR decouples the `VisitWebpageTool` from the core package.
- Reduce the install footprint for users who don't need this tool or prefer an alternative
- Keep core package lean and focused
Related to:
- #1271
=> Remove markdownify as required dependency

src/smolagents/models.py, tests/test_models.py
Fix deprecation of HfApiModel:
- raise `FutureWarning` instead of `DeprecationWarning`: the latter is not intended for end users and is filtered out by default 
- fix warning message specifying in which version the class will be removed
- fix tests: testing deprecated `HfApiModel` raises deprecation warnings in the CI
- explicitly test `HfApiModel` raises deprecation warning when instantiated
Follow up to:
- #1198
=> Fix deprecation of HfApiModel

src/smolagents/default_tools.py
Add Bing search engine to WebSearchTool.
This PR adds the `engine` parameter to WebSearchTool:
- "duckduckgo" (default): DuckDuckGo search engine
- "bing": Bing search engine
As discussed in:
- https://github.com/huggingface/smolagents/pull/1300#issuecomment-2857548400
As proposed by @aymeric-roucher in:
- https://github.com/huggingface/smolagents/issues/1295#issuecomment-2854311665
=> Add Bing search engine to WebSearchTool

tests/test_default_tools.py, tests/test_search.py
Fix CI DuckDuckGoSearchTool tests raising 202 Ratelimit:
- Require RUN_ALL for DuckDuckGoSearchTool calling tests
Fix #1323.
=> Fix CI DuckDuckGoSearchTool tests raising 202 Ratelimit

src/smolagents/agents.py, tests/test_agents.py
Support passing `executor_kwargs` to `LocalPythonExecutor`, aligning its behavior with `RemotePythonExecutor`, which already accepts it.
This PR simplifies configuration and improves consistency across executor types.
With this change, we can now use
```python
agent = CodeAgent(tools=[], model=model, executor_kwargs={"additional_functions": {"open": open}})
```
as functionally equivalent to
```python
agent = CodeAgent(tools=[], model=model)
agent.python_executor.additional_functions = {"open": open}
```
=> Support executor_kwargs in LocalPythonExecutor for initialization customization

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
This PR implements a timeout mechanism for code execution to prevent code from running indefinitely or consuming excessive resources.
As privately discussed with @akseljoonas, certain computations (such as extremely large exponentiations) can lead to unresponsive behavior or exhaust available memory. For example:
```python
log_5_result = 3 ** 2048
log_7_n_result = 5 ** log_5_result
```
To mitigate such risks, this update enforces a configurable timeout limit, ensuring that execution is safely interrupted if it exceeds the allowed duration.
=> Add timeout mechanism for code execution

Makefile
Update Makefile to reflect that `utils` dir was removed in #1218.
=> Remove utils dir from Makefile check_dirs

src/smolagents/models.py
From the Issue : #1343 
Seems like that the api_base and api_keys args were forgot when setting stream_outputs=True in a CodeAgent.
I don't see any reason to not put them in case of a streamed output, so I added them.
Calling a ollama server with custom api_base and stream_outputs=True is now working. 👋
=> add api_base and api_keys to preparation of kwargs for generate stream

src/smolagents/agents.py
Issue #1347. A CodeAgent can't stream and plan at the same time. even if the code line : 
```
if self.stream_outputs and hasattr(self.model, "generate_stream"):
```
Was implemented, the behavior to stream was not right.
I took the same behavior as presented in [_step_stream](https://github.com/huggingface/smolagents/blob/main/src/smolagents/agents.py#L1314C1-L1314C13) and adapted it to the function to stream plan messages.
Now the streaming is working with planning.
=> Fix live streaming when generating planning steps

src/smolagents/models.py
Issue #1349. 
Sometimes LiteLLM send a last message with finish_reason when generation is done.
example : 
```
StreamingChoices(finish_reason='stop', index=0, delta=Delta(provider_specific_fields=None, content=None, role=None, function_call=None, tool_calls=None, audio=None), logprobs=None)
```
The code in generate_stream only check is the key delta is None. But if finish_reason is provided, there might be a Delta object provided under the key delta, but with a content to None. In that case we should not append the None to the generation and we should just stop generation.
=> Stop streaming if LiteLLM provide a finish_reason

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Fix `evaluate_class_def` for Assign Attribute target in `LocalPythonExecutor`.
Currently, the following code raises an error:
```python
class B:
dummy = 1
class A:
b = B()
b.c = "value"
A.b.c
```
> InterpreterError: Code execution failed at line 'A.b.c' due to: AttributeError: 'B' object has no attribute 'c'
Additionally, currently it behaves unexpectedly:
```python
class B:
c = 1
class A:
b = B()
b.c = "value"
A.b.c  # equals 1 instead of "value"
```
=> Fix evaluate_class_def for Assign Attribute target in LocalPythonExecutor

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
Support `pass` statement in class definition in LocalPythonExecutor.
Currently, this code raises an error:
```python
class A:
pass
```
> InterpreterError: Code execution failed at line 'class TestClass: pass' due to: InterpreterError: Unsupported statement in class body: Pass
=> Support 'pass' statement in class definition in LocalPythonExecutor

examples/smolagents_benchmark/run.py, examples/smolagents_benchmark/score.ipynb, src/smolagents/models.py, src/smolagents/monitoring.py
This fixes some bugs introduced by changing token usage reporting in https://github.com/huggingface/smolagents/pull/1337.
In particular, it makes sure to properly serialize model outputs before logging them while running the benchmark.
=> Fix smolagents benchmark

src/smolagents/gradio_ui.py
Improve LaTeX rendering in GradioUI with extended delimiter support.
Fix #1020.
=> Improve LaTeX rendering in GradioUI with extended delimiter support

src/smolagents/agents.py, src/smolagents/local_python_executor.py, tests/test_agents.py, tests/test_local_python_executor.py
An attempt at fixing #1382 
It will accept arbitrary arguments and keywords when calling `final_answer` tool, instead of the unique `answer` argument.
If appropriate please feel free to make changes directly.
Tested locally and only with agent's local python interpreter.
=> Fix: Support custom inputs execution for custom Final Answer Tool

src/smolagents/prompts/code_agent.yaml, src/smolagents/prompts/structured_code_agent.yaml, src/smolagents/prompts/toolcalling_agent.yaml
As outlined in https://github.com/huggingface/smolagents/issues/1292
> Code execution failed at line 'distance_earth_mars = search(query="distance between Earth and Mars")' due to: InterpreterError: Forbidden function evaluation: 'search' is not among the explicitly allowed tools or defined/imported in the preceding code
The prompt is making the agent think that `search` should be used when HF tools [DuckDuckGoSearchTool](https://github.com/huggingface/smolagents/blob/522a315c955a8b0649238d835c23353d8ec54434/src/smolagents/default_tools.py#L102), [GoogleSearchTool](https://github.com/huggingface/smolagents/blob/522a315c955a8b0649238d835c23353d8ec54434/src/smolagents/default_tools.py#L127), [WebSearchTool](https://github.com/huggingface/smolagents/blob/522a315c955a8b0649238d835c23353d8ec544 …
=> Update prompts to avoid confusion: search -> web_search and wiki -> wiki_search

src/smolagents/models.py, tests/test_models.py
Support configurable `tool_choice` in `_prepare_completion_kwargs`.
Note that as reported in the associated issue, some providers do not support `tool_choice="required"`.
Fix #1391.
=> Support configurable tool_choice in prepare_completion_kwargs

src/smolagents/models.py
Support passing additional params to `MLXModel` `load` and `tokenizer.apply_chat_template`.
Fix #1307.
For example, with this PR we can pass `enable_thinking=True` to Qwen3 tokenizer:
```python
model = MLXModel(model_id="Qwen/Qwen3-30B-A3B", apply_chat_template_kwargs={"enable_thinking": True})
```
=> Support passing additional params to MLXModel load and tokenizer.apply_chat_template

src/smolagents/models.py, tests/test_models.py
Always pass `add_generation_prompt=True` to `apply_chat_template`.
This PR passes `add_generation_prompt=True` to `apply_chat_template`, regardless of whether `tools` are provided or not, specifically to:
- VLLMModel
- TransformersModel
Note that before this PR, we always passed `add_generation_prompt=True` regardless of `tools` to:
- MLXModel
The goal is to serve as a basis to continue the discussion on how we want to handle prompt formatting. See previous discussion: https://github.com/huggingface/smolagents/issues/993#issuecomment-2944271019
Based on my own (non-expert) understanding of the [transformers documentation](https://huggingface.co/docs/transformers/main/en/chat_templating#addgenerationprompt), setting `add_generation_prompt=True` appends a generation prompt, which prepares …
=> Always pass add_generation_prompt=True to apply_chat_template

docs/source/en/guided_tour.mdx
Fix ValueError on Guided Tour docs.
Currently, following the docs example raises a ValueError:
> ValueError: Each tool or managed_agent should have a unique name! You passed these duplicate names: ['web_search', 'web_search']
Supersede and close #847.
=> Fix ValueError on Guided Tour docs

docs/source/en/reference/models.mdx, examples/gradio_ui.py, src/smolagents/agents.py, src/smolagents/gradio_ui.py, src/smolagents/memory.py, src/smolagents/models.py, tests/test_agents.py, tests/test_memory.py, tests/test_models.py, tests/test_monitoring.py
This PR change the logic of streaming messages:
- Previously, the logic was to accumulate streaming deltas in the Model classes, and yield objects that "contain all the generated text since start of streaming until now"
- This PR makes the ModelClass directly return atomic streaming deltas, to handle the aggregation only within the agent.
The reason for this is that front-ends like [copilotkit](https://docs.ag-ui.com/concepts/events#textmessagestart) generally expect individual streaming deltas.
Additionally, it removes the `HfApiModel` class, which was deprecated and due for deletion in 1.17, and fuses `Message` into `ChatMessage`
=> Transfer aggregation of streaming events off the Model class

docs/source/en/tutorials/building_good_agents.mdx, docs/source/hi/tutorials/building_good_agents.mdx, docs/source/zh/tutorials/building_good_agents.mdx, src/smolagents/agents.py, src/smolagents/prompts/code_agent.yaml, src/smolagents/prompts/structured_code_agent.yaml, src/smolagents/prompts/toolcalling_agent.yaml
Fix missing mentions of `additional_args` in manager agent prompts.
Follow-up to:
- #1441
- #1456
=> Fix missing mentions of additional_args in manager agent prompts

src/smolagents/default_tools.py
Implement rate limit mechanism in `ApiWebSearchTool`.
Set default to 1 request/second: current limit of Brave Search API Free plan.
=> Implement rate limit mechanism in ApiWebSearchTool

tests/test_models.py
Fix LiteLLM test_call_different_providers_without_key.
Note that different litellm versions produce different error messages.
This PR provides a more robust test that will work with multiple litellm versions.
=> Fix CI LiteLLM test_call_different_providers_without_key

src/smolagents/agent_types.py, src/smolagents/agents.py, src/smolagents/tools.py, tests/test_agents.py
`gradio_client.Client.predict()` returns path to generated images/audio files instead of the real image/audio object: this PR fixes it. It also adds testing to make sure that agents do return image objects when they call `final_answer` on an image.
=> Enable image output for Tool.from_space

src/smolagents/tools.py, tests/test_tools.py
This is a follow-up of #1505, I recently discovered that if the tool's input schema has multiple types while the parsed type is not, the tool calling breaks. The tool calling will return an error:
```
Argument description has type 'string' but should be '[string, null\]'
```
This little PR fixes it.
=> Fix input type validation when input schema has multiple types

docs/source/en/tutorials/tools.md
Fix and improve MCP server security warnings in docs:
- First, fix the repeated mention to `MCPClient` in the same sentence
> The same security warnings mentioned for `MCPClient` apply when using `MCPClient`
- Restructure warnings using the inverted pyramid approach (most critical information first: call to action)
- Make all warnings self-contained rather than referencing previous warning
- Ensure readers who skip to this section get complete information
- Remove the need to search for previous context
These changes follow documentation best practices by ensuring critical security information is immediately visible and complete regardless of how users navigate the documentation.
=> Fix and improve MCP server security warnings in docs

src/smolagents/agents.py
Fixes empty `additional_args` dictionaries being added to agent prompts unnecessarily. The current implementation checks if `additional_args` is not `None`, but doesn't verify if the dictionary actually contains any items.
1. Empty dictionaries were being added to prompts, unnecessarily increasing token usage
2. `ToolCallingAgent` was receiving Python arguments instructions despite not being able to execute Python code
Example prompt when using a nested multi agent strcuture like `CodeAgent` -> `ToolCallingAgent` (Managed Agent)
<pre><code>You're a helpful agent named 'web_agent'.
You have been submitted this task by your manager.
---
Task:
Find at least 3 notable Batman filming locations around the world. For each location, provide the city and country.
---
You're helping your manager …
=> Fix: Prevent empty additional_args from being added to agent prompt

tests/test_agents.py
Temporarily skip wrongly implemented tests.
These tests do not verify the intended behaviors and are therefore misleading, even though they may pass or fail inconsistently. Until we have time to properly rewrite them, they are being explicitly skipped to prevent confusion and inaccurate CI results.
=> Temporarily skip wrongly implemented tests

pyproject.toml
Support mlx-0.26.5.
See: https://github.com/ml-explore/mlx/issues/2390#issuecomment-3091445381
> We are changing the way we release to PyPi. Moving forward the linux cpu-only build you have to specify the [cpu] tag:
`pip install "mlx[cpu]"`
Relevant docs: https://ml-explore.github.io/mlx/build/html/install.html#cpu-only-linux
Fix #1588.
=> Support mlx-0.26.5

src/smolagents/agents.py
In the case when `additional_args` are passed, currently there's a mention of python in the added prompt of `MultiStepAgent`, which makes no sense for a `ToolCallingAgent`: this PR makes the wording more general.
=> Remove mention of python in additional args

src/smolagents/tool_validation.py
I had the following warning :
DeprecationWarning: ast.Num is deprecated and will be removed in Python 3.14; use ast.Constant instead
DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
ast.Str and ast.Num have been deprecated since Python 3.8 and will be removed in Python 3.14. Starting with Python 3.8, all literals (str, int, float, etc.) are represented by ast.Constant.
=> Replace deprecated ast.Num and ast.Str with ast.Constant in tool validation

docs/source/en/tutorials/building_good_agents.md, docs/source/hi/tutorials/building_good_agents.md, docs/source/zh/tutorials/building_good_agents.md, src/smolagents/agents.py, src/smolagents/prompts/code_agent.yaml, src/smolagents/prompts/structured_code_agent.yaml, src/smolagents/prompts/toolcalling_agent.yaml, src/smolagents/tools.py, src/smolagents/utils.py, tests/fixtures/tools.py, tests/test_tools.py
Add `to_code_prompt` and `to_tool_calling_prompt` methods to Tool class.
This PR represents the first step in a broader refactoring of the tools system.
This PR introduces two new methods to the `Tool` class to improve and generalize template rendering:
- `to_code_prompt()`: Generate properly formatted Python function definitions with docstrings for code agent prompts
- `to_tool_calling_prompt()`: Generate tool descriptions for tool-calling agent prompts
- Update Jinja templates and replace hardcoded YAML generation with method calls
- Added comprehensive pytest test suite covering:
- Tools with no inputs
- Tools with single/multiple inputs
- Multi-line descriptions
=> Add Tool to_code_prompt and to_tool_calling_prompt

src/smolagents/models.py
Support passing `model_kwargs` to `TransformersModel`, similar to other model classes like `VLLMModel`.
Supersede and close #1168.
=> ENH: Support passing model_kwargs to TransformersModel

src/smolagents/gradio_ui.py
Reset agent memory when the clear button is clicked in the Gradio chatbot interface.
Close #1609.
=> Reset agent memory on GradioUI clear button

src/smolagents/remote_executors.py, tests/test_remote_executors.py
In `RemotePythonExecutor`, I think we do not need to run any code if there are no variables passed to `send_variables`.
=> Do not send variables if there is not any RemotePythonExecutor

pyproject.toml
CI hotfix: Pin transformers < 4.54.0.
Fix #1619.
=> CI hotfix: Pin transformers < 4.54.0

src/smolagents/agents.py, tests/test_agents.py, tests/test_monitoring.py
Currently in `ToolCallingAgent`, `memory_step.model_output` is augmented by appending a formatted string representing every tool call.
- I think it is not necessary. It was originally intended to better visualize tool calls in Gradio interfaces. But these interfaces now visualize the content of `step.tool_calls` directly
- it has the unintended effect of showing LLMs a wrong history of past messages. The artifact that it created for me is that the model would see tool call descriptions in history, thus it would start to write itself `Tool call {id}: calling {name} with {arguments}` instead of using JSON action format.
Thus we can remove it!
=> ToolCallingAgent: remove unncessary addition to model_output

src/smolagents/agents.py, src/smolagents/tools.py, tests/test_tools.py
Make `validate_tool_arguments` raise exception instead of returning error string, improving code design and following Python conventions.
- **Updated `validate_tool_arguments`**: Now raises `ValueError` and `TypeError` directly instead of returning error message strings
- **Removed periods from error messages**: Following Python best practices for exception messages
- **Updated docstring**: Added comprehensive `Raises` section documenting all possible exceptions
- **Updated tests**: Modified `test_validate_tool_arguments` and `test_validate_tool_arguments_nullable` to use `pytest.raises()` for exception testing
- **Simplified caller code**: The caller in `execute_tool_call` now has cleaner exception handling with proper exception chaining using `from e`
1. **Removes tight coupling**: The …
=> Make validate_tool_arguments raise exception instead of returning error string

src/smolagents/local_python_executor.py, tests/test_local_python_executor.py
The proposed fix is to make continue statements break from the current execution of the loop body and continue to the next loop iteration.
The local python interpreter incorrectly handles continue statements within `for` loops. A `continue` statement is treated as a `pass` statement which silently breaks normal Python semantics.
```python
from smolagents.local_python_executor import LocalPythonExecutor, BASE_PYTHON_TOOLS
program = """for i in range(5):
continue
print(i)"""
executor = LocalPythonExecutor(additional_authorized_imports=[])
executor.send_tools(BASE_PYTHON_TOOLS)
print(executor(program).logs)
```
Output:
```
0
1
2
3
4
```
The output from the above code is incorrect based on the semantics of a Python `continue` statement which should skip to the next loop iteration rather than …
=> Bug Fix: Fix continue semantics of LocalPythonExecutor

src/smolagents/local_python_executor.py, src/smolagents/remote_executors.py
This PR enriches the details of the `PythonExecutor` class:
1. Added method declaration.
2. Declares its inherited abstract base class.
Hope this small change will allow others to get more LSP hints when using this class:)
=> refactor(PythonExecutor): inherit from ABC and declare abstract methods

src/smolagents/models.py
The `gpt-5`, `gpt-5-mini`, and `gpt-5-nano` models do not support the `stop` parameter.
```console
smolagents.utils.AgentGenerationError: Error while generating output:
Error code: 400 - {'error': {'message': "Unsupported parameter: 'stop' is not supported with this model.", 'type': 'invalid_request_error', 'param': 'stop', 'code': 'unsupported_parameter'}}
```
=> Fix error for GPT-5 not supporting the `stop` parameter

src/smolagents/agents.py, tests/test_monitoring.py
I find myself often mistakenly passing argument `return_full_result` in the `run()` method instead of agent initialization: 
and indeed the choice to return full results can be run-specific rather than agent-specific. Thus I think it would be best to integrate this arg in the run() method as well.
=> Enable return_full_result directly in run method

pyproject.toml
Support openai 1.100 for litellm extra.
Close #1697.
=> Support openai 1.100 for litellm extra

pyproject.toml
Pin openinference-instrumentation-smolagents>=0.1.15 to use new TokenUsage structure
Fix #1682.
=> Pin telemetry extra >=0.1.15 to use new TokenUsage structure

docs/source/en/guided_tour.md, docs/source/en/reference/tools.md, docs/source/en/tutorials/building_good_agents.md, docs/source/en/tutorials/tools.md, examples/structured_output_tool.py, pyproject.toml, src/smolagents/mcp_client.py, src/smolagents/prompts/code_agent.yaml, src/smolagents/tools.py, tests/test_mcp_client.py, tests/test_tools.py
This PR implements structured output and output schema support for smolagents, leveraging [MCPAdapt >= 0.1.13](https://github.com/grll/mcpadapt/releases/tag/v0.1.13) capabilities to enable MCP tools that return complex structured data with defined output schemas. Changes are fully backwards compatible and opt-in only.
**The key advantage is that the agent LLM sees what to expect from a tool call before calling the tool, without the need for `print(tool_output)`.**
The latest [MCP specifications (2025-06-18+)](https://modelcontextprotocol.io/specification/2025-06-18/server/tools#output-schema) include support for `outputSchema`, enabling tools to return [structured data](https://modelcontextprotocol.io/specification/2025-06-18/server/tools#structured-content) with defined schemas. This …
=> Support MCP structured output and output schema

src/smolagents/agents.py, tests/test_agents.py
**Context**
I use `smolagents` to create a multimodel agent running an on-device VLM via `llama-server` and found inference to be quite slow. Looking at the logs, I realized that the image inputs are being processed in every VLM call (or agent step), which takes up a lot of processing time (2 seconds for each image). Ideally, the images should be processed once as the latent representations are already saved in the KV cache.
**Changes proposed**
We should not include images into ActionSteps in `agent.run` as they are already included in the TaskStep and saved to `agent.memory`. In other words, we only initialize images once in `agent.memory`. This allows the underlying VLM to process the images only once during the initial prefill and reduce latency for subsequent steps by exploiting the …
=> Improve agent image handling

tests/test_default_tools.py
Fix CI 403 error for Wikipedia page in test_visit_webpage.
This PR changes the URL in test_visit_webpage to avoid the 403 Forbidden error.
=> Fix CI 403 error for Wikipedia page in test_visit_webpage

src/smolagents/prompts/code_agent.yaml
Fixing CodeAgent system prompt that contained an example of Python code with a syntax error. Additionally, fixing some typos and consistency issues.
=> fix typos in the system prompt

tests/test_agents.py
Fix deprecation warning about parameter `messages`: https://github.com/huggingface/smolagents/actions/runs/17234970996/job/48897627718?pr=1690
> FutureWarning: Parameter 'messages' is deprecated and will be removed in version 1.25. Please use 'steps' instead.
```python
tests/test_agents.py::TestRunResult::test_no_token_usage[CodeAgent]
tests/test_agents.py::TestRunResult::test_no_token_usage[ToolCallingAgent]
/home/runner/work/smolagents/smolagents/tests/test_agents.py:887: FutureWarning: Parameter 'messages' is deprecated and will be removed in version 1.25. Please use 'steps' instead.
assert isinstance(result.messages, list)
tests/test_agents.py::TestRunResult::test_full_result[True-None-True]
tests/test_agents.py::TestRunResult::test_full_result[False-True-True] …
```
=> Fix deprecation warning about parameter messages

README.md, SECURITY.md, docs/source/en/reference/agents.md, docs/source/en/tutorials/secure_code_execution.md, examples/sandboxed_execution.py, pyproject.toml, src/smolagents/agents.py, src/smolagents/remote_executors.py, tests/test_remote_executors.py
This PR adds a remote executor backed by [Modal](https://modal.com/), by setting `executor_type="modal"`.
The Modal executor shares many of the same functionality as the `DockerExecutor` when it comes to creating an image with a `jupyter_kernel_gateway` and using websockets to talk to the container. With this PR:
1. The shared functionality is refactored into it's own functions and used between the `ModalExecutor` and `DockerExecutor`.
2. The integration tests for docker is refactored into a `CommonDockerExecutorIntegration` which is subclassed by `TestDockerExecutorIntegration` and `TestModalExecutorIntegration`.
3. `CodeAgent` can now accept a `executor_type="modal"`.
=> Adds Modal Remote Executor

docs/source/ko/_toctree.yml
Fix formatting of title in translation section of documentation `_toctree.yml` file.
Fix #1726.
CC: @stevhliu
=> Fix formatting of title in translation section of documentation

docs/source/ko/_toctree.yml
Remove untranslated sections from the documentation `_toctree.yml` file..
Fix #1728.
CC: @stevhliu
=> Remove untranslated sections from the documentation

src/smolagents/agents.py
When plan_message.token_usage is None, the code was assigning (None, None) to input_tokens and output_tokens, which later caused UnboundLocalError when creating TokenUsage objects that expect integer values.
This fix changes the fallback from (None, None) to (0, 0) to ensure token usage tracking works correctly even when token usage information is unavailable from the LLM provider.
Fixes issue where agent planning step crashes with: 'cannot access local variable "input_tokens" where it is not associated with a value'
=> Fix token count initialization when plan_message.token_usage is None

docs/source/en/tutorials/building_good_agents.md
Added a note in `docs/source/en/tutorials/building_good_agents.md` explaining that the `instructions` parameter is appended to the system prompt, rather than replacing it.
=> Update documentation to clarify `instructions` are appended

src/smolagents/agents.py
Fix `AttributeError` when trying to log a None.
This pull request makes a minor update to the `_step_stream` method in `src/smolagents/agents.py` to improve logging robustness. The change ensures that the logger always receives a string, preventing AttributeError if `output_text` is `None`.
Fix #1785.
=> Fix AttributeError when trying to log a None

src/smolagents/agents.py
This PR removes the unused `get_variable_names` function from `src/smolagents/agents.py` that was introduced in commit 8ba036bba0392b36b72d0e60e808cfe7e329b954.
The `get_variable_names` function is dead code that:
- Has no callers anywhere in the codebase
- Has no test coverage
- Is not referenced in documentation
- Contributes to unnecessary code bloat
Removing unused code improves:
- Code maintainability
- Codebase clarity
- Reduces potential confusion for developers
- Removed the `get_variable_names` function (lines 101-103) and `import re` from `src/smolagents/agents.py`
**Note**: This function was originally introduced in [commit 8ba036b](https://github.com/huggingface/smolagents/commit/8ba036bba0392b36b72d0e60e808cfe7e329b954) but never actually used in the codebase.
=> fix(agent): remove unused get_variable_names function
